enum Countries {
    HongKong,
    Iraq,
    Germany,
    CentralAfricanRepublic,
    Albania,
    Qatar,
    Nicaragua,
    Guernsey,
    Burundi,
    Brazil,
    SaudiArabia,
    Croatia,
    Honduras,
    Indonesia,
    Tunisia,
    ElSalvador,
    Bahrain,
    Nigeria,
    NorthernMarianaIslands,
    EuropeanUnion,
    WesternSahara,
    PapuaNewGuinea,
    Australia,
    Dominica,
    Botswana,
    Palau,
    Iran,
    Argentina,
    GuineaBissau,
    CapeVerde,
    NewCaledonia,
    Anguilla,
    Chile,
    Benin,
    Uruguay,
    Lithuania,
    Bahamas,
    HeardIslandAndMcdonaldIslands,
    Ireland,
    Nepal,
    SaintKittsAndNevis,
    Mozambique,
    CaymanIslands,
    Ukraine,
    Vietnam,
    Haiti,
    Angola,
    Cambodia,
    Philippines,
    Israel,
    Myanmar,
    England,
    Moldova,
    Catalonia,
    NorthKorea,
    Panama,
    AmericanSamoa,
    Zimbabwe,
    Canada,
    EastAfricanCommunity,
    Sweden,
    PacificCommunity,
    AlandIslands,
    Nauru,
    SaintHelenaAscension,
    Belarus,
    Tanzania,
    Uganda,
    Lesotho,
    Afghanistan,
    CookIslands,
    Switzerland,
    NorfolkIsland,
    SriLanka,
    UnitedStates,
    Serbia,
    SaintBarthelemy,
    Cyprus,
    UnitedArabEmirates,
    PitcairnIslands,
    Japan,
    FrenchPolynesia,
    Samoa,
    Guadeloupe,
    Brunei,
    Aruba,
    SaintVincentAndTheGrenadines,
    IsleOfMan,
    VaticanCity,
    SintMaarten,
    Poland,
    Colombia,
    Curacao,
    Kosovo,
    SvalbardAndJanMayen,
    Hungary,
    IvoryCoast,
    Kiribati,
    Grenada,
    Slovenia,
    Uzbekistan,
    Pakistan,
    AntiguaAndBarbuda,
    Kyrgyzstan,
    Malta,
    Kuwait,
    Namibia,
    Suriname,
    FaroeIslands,
    Spain,
    Martinique,
    BritishIndianOceanTerritory,
    Montenegro,
    Barbados,
    Antarctica,
    Somalia,
    Chad,
    Senegal,
    Peru,
    Morocco,
    Turkey,
    Estonia,
    Macau,
    FalklandIslands,
    Tokelau,
    Azerbaijan,
    Ghana,
    Bolivia,
    Palestine,
    Madagascar,
    Jersey,
    TrinidadAndTobago,
    Mauritania,
    Greece,
    Micronesia,
    Jamaica,
    DemocraticRepublicOfTheCongo,
    Tonga,
    Luxembourg,
    Lebanon,
    WallisAndFutuna,
    CostaRica,
    ClippertonIsland,
    Bermuda,
    Denmark,
    MarshallIslands,
    Monaco,
    Laos,
    Zambia,
    Maldives,
    Fiji,
    DominicanRepublic,
    Wales,
    Ecuador,
    Venezuela,
    Andorra,
    FrenchSouthernAndAntarcticLands,
    Montserrat,
    BouvetIsland,
    ShSvg,
    BurkinaFaso,
    TurksAndCaicosIslands,
    Mayotte,
    Austria,
    Latvia,
    CanaryIslands,
    Taiwan,
    Bulgaria,
    Reunion,
    Niger,
    Armenia,
    UnitedStatesVirginIslands,
    Seychelles,
    Liechtenstein,
    BosniaAndHerzegovina,
    UnitedNations,
    ArabWorld,
    BasqueCountry,
    India,
    TristanDaCunha,
    Mexico,
    Scotland,
    NewZealand,
    Tajikistan,
    Kenya,
    Eswatini,
    Romania,
    Tuvalu,
    Paraguay,
    Guam,
    CentralEuropeanFreeTradeAgreement,
    Egypt,
    Comoros,
    Liberia,
    Gabon,
    SouthAfrica,
    Syria,
    FrenchGuiana,
    Guyana,
    Bangladesh,
    Turkmenistan,
    Mali,
    BritishVirginIslands,
    Mauritius,
    NorthMacedonia,
    Mongolia,
    Singapore,
    Libya,
    Georgia,
    Oman,
    TimorLeste,
    Kazakhstan,
    SierraLeone,
    ChristmasIsland,
    SaintLucia,
    Sudan,
    PuertoRico,
    Cameroon,
    SouthSudan,
    EquatorialGuinea,
    UnknownCountry,
    Bhutan,
    SouthKorea,
    Vanuatu,
    Guinea,
    Belgium,
    Djibouti,
    France,
    Finland,
    AssociationOfSoutheastAsianNations,
    BonaireSaintEustatiusAndSaba,
    Guatemala,
    Russia,
    NorthernIreland,
    SaoTomeAndPrincipe,
    Greenland,
    Ethiopia,
    UnitedStatesMinorOutlyingIslands,
    CocosKeelingIslands,
    Gambia,
    China,
    Italy,
    SaintPierreAndMiquelon,
    DiegoGarcia,
    SaintHelena,
    Malaysia,
    Yemen,
    Jordan,
    Niue,
    Eritrea,
    Belize,
    Netherlands,
    SouthGeorgiaAndTheSouthSandwichIslands,
    Gibraltar,
    Portugal,
    RepublicOfTheCongo,
    Togo,
    CzechRepublic,
    SaintMartin,
    Thailand,
    Rwanda,
    Slovakia,
    SolomonIslands,
    Malawi,
    Norway,
    SanMarino,
    Galicia,
    Cuba,
    Iceland,
    Algeria,
    UnitedKingdom,
}

impl Countries {
    fn from_str(s: &str) -> Result<Self> {
        match s {
            "hong-kong" => Ok(Countries::HongKong),
            "iraq" => Ok(Countries::Iraq),
            "germany" => Ok(Countries::Germany),
            "central-african-republic" => Ok(Countries::CentralAfricanRepublic),
            "albania" => Ok(Countries::Albania),
            "qatar" => Ok(Countries::Qatar),
            "nicaragua" => Ok(Countries::Nicaragua),
            "guernsey" => Ok(Countries::Guernsey),
            "burundi" => Ok(Countries::Burundi),
            "brazil" => Ok(Countries::Brazil),
            "saudi-arabia" => Ok(Countries::SaudiArabia),
            "croatia" => Ok(Countries::Croatia),
            "honduras" => Ok(Countries::Honduras),
            "indonesia" => Ok(Countries::Indonesia),
            "tunisia" => Ok(Countries::Tunisia),
            "el-salvador" => Ok(Countries::ElSalvador),
            "bahrain" => Ok(Countries::Bahrain),
            "nigeria" => Ok(Countries::Nigeria),
            "northern-mariana-islands" => Ok(Countries::NorthernMarianaIslands),
            "european-union" => Ok(Countries::EuropeanUnion),
            "western-sahara" => Ok(Countries::WesternSahara),
            "papua-new-guinea" => Ok(Countries::PapuaNewGuinea),
            "australia" => Ok(Countries::Australia),
            "dominica" => Ok(Countries::Dominica),
            "botswana" => Ok(Countries::Botswana),
            "palau" => Ok(Countries::Palau),
            "iran" => Ok(Countries::Iran),
            "argentina" => Ok(Countries::Argentina),
            "guinea-bissau" => Ok(Countries::GuineaBissau),
            "cape-verde" => Ok(Countries::CapeVerde),
            "new-caledonia" => Ok(Countries::NewCaledonia),
            "anguilla" => Ok(Countries::Anguilla),
            "chile" => Ok(Countries::Chile),
            "benin" => Ok(Countries::Benin),
            "uruguay" => Ok(Countries::Uruguay),
            "lithuania" => Ok(Countries::Lithuania),
            "bahamas" => Ok(Countries::Bahamas),
            "heard-island-and-mcdonald-islands" => Ok(Countries::HeardIslandAndMcdonaldIslands),
            "ireland" => Ok(Countries::Ireland),
            "nepal" => Ok(Countries::Nepal),
            "saint-kitts-and-nevis" => Ok(Countries::SaintKittsAndNevis),
            "mozambique" => Ok(Countries::Mozambique),
            "cayman-islands" => Ok(Countries::CaymanIslands),
            "ukraine" => Ok(Countries::Ukraine),
            "vietnam" => Ok(Countries::Vietnam),
            "haiti" => Ok(Countries::Haiti),
            "angola" => Ok(Countries::Angola),
            "cambodia" => Ok(Countries::Cambodia),
            "philippines" => Ok(Countries::Philippines),
            "israel" => Ok(Countries::Israel),
            "myanmar" => Ok(Countries::Myanmar),
            "england" => Ok(Countries::England),
            "moldova" => Ok(Countries::Moldova),
            "catalonia" => Ok(Countries::Catalonia),
            "north-korea" => Ok(Countries::NorthKorea),
            "panama" => Ok(Countries::Panama),
            "american-samoa" => Ok(Countries::AmericanSamoa),
            "zimbabwe" => Ok(Countries::Zimbabwe),
            "canada" => Ok(Countries::Canada),
            "east-african-community" => Ok(Countries::EastAfricanCommunity),
            "sweden" => Ok(Countries::Sweden),
            "pacific-community" => Ok(Countries::PacificCommunity),
            "aland-islands" => Ok(Countries::AlandIslands),
            "nauru" => Ok(Countries::Nauru),
            "saint-helena-ascension" => Ok(Countries::SaintHelenaAscension),
            "belarus" => Ok(Countries::Belarus),
            "tanzania" => Ok(Countries::Tanzania),
            "uganda" => Ok(Countries::Uganda),
            "lesotho" => Ok(Countries::Lesotho),
            "afghanistan" => Ok(Countries::Afghanistan),
            "cook-islands" => Ok(Countries::CookIslands),
            "switzerland" => Ok(Countries::Switzerland),
            "norfolk-island" => Ok(Countries::NorfolkIsland),
            "sri-lanka" => Ok(Countries::SriLanka),
            "united-states" => Ok(Countries::UnitedStates),
            "serbia" => Ok(Countries::Serbia),
            "saint-barthelemy" => Ok(Countries::SaintBarthelemy),
            "cyprus" => Ok(Countries::Cyprus),
            "united-arab-emirates" => Ok(Countries::UnitedArabEmirates),
            "pitcairn-islands" => Ok(Countries::PitcairnIslands),
            "japan" => Ok(Countries::Japan),
            "french-polynesia" => Ok(Countries::FrenchPolynesia),
            "samoa" => Ok(Countries::Samoa),
            "guadeloupe" => Ok(Countries::Guadeloupe),
            "brunei" => Ok(Countries::Brunei),
            "aruba" => Ok(Countries::Aruba),
            "saint-vincent-and-the-grenadines" => Ok(Countries::SaintVincentAndTheGrenadines),
            "isle-of-man" => Ok(Countries::IsleOfMan),
            "vatican-city" => Ok(Countries::VaticanCity),
            "sint-maarten" => Ok(Countries::SintMaarten),
            "poland" => Ok(Countries::Poland),
            "colombia" => Ok(Countries::Colombia),
            "curacao" => Ok(Countries::Curacao),
            "kosovo" => Ok(Countries::Kosovo),
            "svalbard-and-jan-mayen" => Ok(Countries::SvalbardAndJanMayen),
            "hungary" => Ok(Countries::Hungary),
            "ivory-coast" => Ok(Countries::IvoryCoast),
            "kiribati" => Ok(Countries::Kiribati),
            "grenada" => Ok(Countries::Grenada),
            "slovenia" => Ok(Countries::Slovenia),
            "uzbekistan" => Ok(Countries::Uzbekistan),
            "pakistan" => Ok(Countries::Pakistan),
            "antigua-and-barbuda" => Ok(Countries::AntiguaAndBarbuda),
            "kyrgyzstan" => Ok(Countries::Kyrgyzstan),
            "malta" => Ok(Countries::Malta),
            "kuwait" => Ok(Countries::Kuwait),
            "namibia" => Ok(Countries::Namibia),
            "suriname" => Ok(Countries::Suriname),
            "faroe-islands" => Ok(Countries::FaroeIslands),
            "spain" => Ok(Countries::Spain),
            "martinique" => Ok(Countries::Martinique),
            "british-indian-ocean-territory" => Ok(Countries::BritishIndianOceanTerritory),
            "montenegro" => Ok(Countries::Montenegro),
            "barbados" => Ok(Countries::Barbados),
            "antarctica" => Ok(Countries::Antarctica),
            "somalia" => Ok(Countries::Somalia),
            "chad" => Ok(Countries::Chad),
            "senegal" => Ok(Countries::Senegal),
            "peru" => Ok(Countries::Peru),
            "morocco" => Ok(Countries::Morocco),
            "turkey" => Ok(Countries::Turkey),
            "estonia" => Ok(Countries::Estonia),
            "macau" => Ok(Countries::Macau),
            "falkland-islands" => Ok(Countries::FalklandIslands),
            "tokelau" => Ok(Countries::Tokelau),
            "azerbaijan" => Ok(Countries::Azerbaijan),
            "ghana" => Ok(Countries::Ghana),
            "bolivia" => Ok(Countries::Bolivia),
            "palestine" => Ok(Countries::Palestine),
            "madagascar" => Ok(Countries::Madagascar),
            "jersey" => Ok(Countries::Jersey),
            "trinidad-and-tobago" => Ok(Countries::TrinidadAndTobago),
            "mauritania" => Ok(Countries::Mauritania),
            "greece" => Ok(Countries::Greece),
            "micronesia" => Ok(Countries::Micronesia),
            "jamaica" => Ok(Countries::Jamaica),
            "democratic-republic-of-the-congo" => Ok(Countries::DemocraticRepublicOfTheCongo),
            "tonga" => Ok(Countries::Tonga),
            "luxembourg" => Ok(Countries::Luxembourg),
            "lebanon" => Ok(Countries::Lebanon),
            "wallis-and-futuna" => Ok(Countries::WallisAndFutuna),
            "costa-rica" => Ok(Countries::CostaRica),
            "clipperton-island" => Ok(Countries::ClippertonIsland),
            "bermuda" => Ok(Countries::Bermuda),
            "denmark" => Ok(Countries::Denmark),
            "marshall-islands" => Ok(Countries::MarshallIslands),
            "monaco" => Ok(Countries::Monaco),
            "laos" => Ok(Countries::Laos),
            "zambia" => Ok(Countries::Zambia),
            "maldives" => Ok(Countries::Maldives),
            "fiji" => Ok(Countries::Fiji),
            "dominican-republic" => Ok(Countries::DominicanRepublic),
            "wales" => Ok(Countries::Wales),
            "ecuador" => Ok(Countries::Ecuador),
            "venezuela" => Ok(Countries::Venezuela),
            "andorra" => Ok(Countries::Andorra),
            "french-southern-and-antarctic-lands" => Ok(Countries::FrenchSouthernAndAntarcticLands),
            "montserrat" => Ok(Countries::Montserrat),
            "bouvet-island" => Ok(Countries::BouvetIsland),
            "sh.svg" => Ok(Countries::ShSvg),
            "burkina-faso" => Ok(Countries::BurkinaFaso),
            "turks-and-caicos-islands" => Ok(Countries::TurksAndCaicosIslands),
            "mayotte" => Ok(Countries::Mayotte),
            "austria" => Ok(Countries::Austria),
            "latvia" => Ok(Countries::Latvia),
            "canary-islands" => Ok(Countries::CanaryIslands),
            "taiwan" => Ok(Countries::Taiwan),
            "bulgaria" => Ok(Countries::Bulgaria),
            "reunion" => Ok(Countries::Reunion),
            "niger" => Ok(Countries::Niger),
            "armenia" => Ok(Countries::Armenia),
            "united-states-virgin-islands" => Ok(Countries::UnitedStatesVirginIslands),
            "seychelles" => Ok(Countries::Seychelles),
            "liechtenstein" => Ok(Countries::Liechtenstein),
            "bosnia-and-herzegovina" => Ok(Countries::BosniaAndHerzegovina),
            "united-nations" => Ok(Countries::UnitedNations),
            "arab-world" => Ok(Countries::ArabWorld),
            "basque-country" => Ok(Countries::BasqueCountry),
            "india" => Ok(Countries::India),
            "tristan-da-cunha" => Ok(Countries::TristanDaCunha),
            "mexico" => Ok(Countries::Mexico),
            "scotland" => Ok(Countries::Scotland),
            "new-zealand" => Ok(Countries::NewZealand),
            "tajikistan" => Ok(Countries::Tajikistan),
            "kenya" => Ok(Countries::Kenya),
            "eswatini" => Ok(Countries::Eswatini),
            "romania" => Ok(Countries::Romania),
            "tuvalu" => Ok(Countries::Tuvalu),
            "paraguay" => Ok(Countries::Paraguay),
            "guam" => Ok(Countries::Guam),
            "central-european-free-trade-agreement" => {
                Ok(Countries::CentralEuropeanFreeTradeAgreement)
            }
            "egypt" => Ok(Countries::Egypt),
            "comoros" => Ok(Countries::Comoros),
            "liberia" => Ok(Countries::Liberia),
            "gabon" => Ok(Countries::Gabon),
            "south-africa" => Ok(Countries::SouthAfrica),
            "syria" => Ok(Countries::Syria),
            "french-guiana" => Ok(Countries::FrenchGuiana),
            "guyana" => Ok(Countries::Guyana),
            "bangladesh" => Ok(Countries::Bangladesh),
            "turkmenistan" => Ok(Countries::Turkmenistan),
            "mali" => Ok(Countries::Mali),
            "british-virgin-islands" => Ok(Countries::BritishVirginIslands),
            "mauritius" => Ok(Countries::Mauritius),
            "north-macedonia" => Ok(Countries::NorthMacedonia),
            "mongolia" => Ok(Countries::Mongolia),
            "singapore" => Ok(Countries::Singapore),
            "libya" => Ok(Countries::Libya),
            "georgia" => Ok(Countries::Georgia),
            "oman" => Ok(Countries::Oman),
            "timor-leste" => Ok(Countries::TimorLeste),
            "kazakhstan" => Ok(Countries::Kazakhstan),
            "sierra-leone" => Ok(Countries::SierraLeone),
            "christmas-island" => Ok(Countries::ChristmasIsland),
            "saint-lucia" => Ok(Countries::SaintLucia),
            "sudan" => Ok(Countries::Sudan),
            "puerto-rico" => Ok(Countries::PuertoRico),
            "cameroon" => Ok(Countries::Cameroon),
            "south-sudan" => Ok(Countries::SouthSudan),
            "equatorial-guinea" => Ok(Countries::EquatorialGuinea),
            "unknown-country" => Ok(Countries::UnknownCountry),
            "bhutan" => Ok(Countries::Bhutan),
            "south-korea" => Ok(Countries::SouthKorea),
            "vanuatu" => Ok(Countries::Vanuatu),
            "guinea" => Ok(Countries::Guinea),
            "belgium" => Ok(Countries::Belgium),
            "djibouti" => Ok(Countries::Djibouti),
            "france" => Ok(Countries::France),
            "finland" => Ok(Countries::Finland),
            "association-of-southeast-asian-nations" => {
                Ok(Countries::AssociationOfSoutheastAsianNations)
            }
            "bonaire-saint-eustatius-and-saba" => Ok(Countries::BonaireSaintEustatiusAndSaba),
            "guatemala" => Ok(Countries::Guatemala),
            "russia" => Ok(Countries::Russia),
            "northern-ireland" => Ok(Countries::NorthernIreland),
            "sao-tome-and-principe" => Ok(Countries::SaoTomeAndPrincipe),
            "greenland" => Ok(Countries::Greenland),
            "ethiopia" => Ok(Countries::Ethiopia),
            "united-states-minor-outlying-islands" => {
                Ok(Countries::UnitedStatesMinorOutlyingIslands)
            }
            "cocos-keeling-islands" => Ok(Countries::CocosKeelingIslands),
            "gambia" => Ok(Countries::Gambia),
            "china" => Ok(Countries::China),
            "italy" => Ok(Countries::Italy),
            "saint-pierre-and-miquelon" => Ok(Countries::SaintPierreAndMiquelon),
            "diego-garcia" => Ok(Countries::DiegoGarcia),
            "saint-helena" => Ok(Countries::SaintHelena),
            "malaysia" => Ok(Countries::Malaysia),
            "yemen" => Ok(Countries::Yemen),
            "jordan" => Ok(Countries::Jordan),
            "niue" => Ok(Countries::Niue),
            "eritrea" => Ok(Countries::Eritrea),
            "belize" => Ok(Countries::Belize),
            "netherlands" => Ok(Countries::Netherlands),
            "south-georgia-and-the-south-sandwich-islands" => {
                Ok(Countries::SouthGeorgiaAndTheSouthSandwichIslands)
            }
            "gibraltar" => Ok(Countries::Gibraltar),
            "portugal" => Ok(Countries::Portugal),
            "republic-of-the-congo" => Ok(Countries::RepublicOfTheCongo),
            "togo" => Ok(Countries::Togo),
            "czech-republic" => Ok(Countries::CzechRepublic),
            "saint-martin" => Ok(Countries::SaintMartin),
            "thailand" => Ok(Countries::Thailand),
            "rwanda" => Ok(Countries::Rwanda),
            "slovakia" => Ok(Countries::Slovakia),
            "solomon-islands" => Ok(Countries::SolomonIslands),
            "malawi" => Ok(Countries::Malawi),
            "norway" => Ok(Countries::Norway),
            "san-marino" => Ok(Countries::SanMarino),
            "galicia" => Ok(Countries::Galicia),
            "cuba" => Ok(Countries::Cuba),
            "iceland" => Ok(Countries::Iceland),
            "algeria" => Ok(Countries::Algeria),
            "united-kingdom" => Ok(Countries::UnitedKingdom),
            _ => Err(),
        }
    }
    fn from_country_code(s: &str) -> Result<Self, ()> {
        match s {
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            "gb" => Err(()),
            _ => Err(),
        }
    }
}
