//! This file is @generated by `countries.rkyv.generate.rs`,
//! and contains Rust data structures generated from countries JSON
use crate::countries::COUNTRIES_DATA;
use crate::countries::Country;
#[rustfmt::skip]
#[derive(
    Eq,
    PartialEq,
    Copy,
    Clone,
    Ord,
    PartialOrd,
    Debug,
    clap::ValueEnum,
    strum::VariantArray
)]
#[clap(rename_all = "PascalCase")]
pub enum CountryKind {
    #[clap(alias = "AW")]
    #[clap(alias = "AW")]
    Aruba,
    #[clap(alias = "AF")]
    #[clap(alias = "AF")]
    #[clap(alias = "Afġānistān")]
    Afghanistan,
    #[clap(alias = "AO")]
    #[clap(alias = "AO")]
    #[clap(alias = "República de Angola")]
    #[clap(alias = "ʁɛpublika de an'ɡɔla")]
    Angola,
    #[clap(alias = "AI")]
    #[clap(alias = "AI")]
    Anguilla,
    #[clap(alias = "AX")]
    #[clap(alias = "AX")]
    #[clap(alias = "Aaland")]
    #[clap(alias = "Aland")]
    #[clap(alias = "Ahvenanmaa")]
    AlandIslands,
    #[clap(alias = "AL")]
    #[clap(alias = "AL")]
    #[clap(alias = "Shqipëri")]
    #[clap(alias = "Shqipëria")]
    #[clap(alias = "Shqipnia")]
    Albania,
    #[clap(alias = "AD")]
    #[clap(alias = "AD")]
    #[clap(alias = "Principality of Andorra")]
    #[clap(alias = "Principat d'Andorra")]
    Andorra,
    #[clap(alias = "AE")]
    #[clap(alias = "AE")]
    #[clap(alias = "UAE")]
    #[clap(alias = "Emirates")]
    UnitedArabEmirates,
    #[clap(alias = "AR")]
    #[clap(alias = "AR")]
    #[clap(alias = "Argentine Republic")]
    #[clap(alias = "República Argentina")]
    Argentina,
    #[clap(alias = "AM")]
    #[clap(alias = "AM")]
    #[clap(alias = "Hayastan")]
    #[clap(alias = "Republic of Armenia")]
    #[clap(alias = "Հայաստանի Հանրապետություն")]
    Armenia,
    #[clap(alias = "AS")]
    #[clap(alias = "AS")]
    #[clap(alias = "Amerika Sāmoa")]
    #[clap(alias = "Amelika Sāmoa")]
    #[clap(alias = "Sāmoa Amelika")]
    AmericanSamoa,
    #[clap(alias = "AQ")]
    #[clap(alias = "AQ")]
    Antarctica,
    #[clap(alias = "TF")]
    #[clap(alias = "TF")]
    #[clap(alias = "French Southern Territories")]
    FrenchSouthernAndAntarcticLands,
    #[clap(alias = "AG")]
    #[clap(alias = "AG")]
    AntiguaAndBarbuda,
    #[clap(alias = "AU")]
    #[clap(alias = "AU")]
    Australia,
    #[clap(alias = "AT")]
    #[clap(alias = "AT")]
    #[clap(alias = "Osterreich")]
    #[clap(alias = "Oesterreich")]
    Austria,
    #[clap(alias = "AZ")]
    #[clap(alias = "AZ")]
    #[clap(alias = "Republic of Azerbaijan")]
    #[clap(alias = "Azərbaycan Respublikası")]
    Azerbaijan,
    #[clap(alias = "BI")]
    #[clap(alias = "BI")]
    #[clap(alias = "Republic of Burundi")]
    #[clap(alias = "Republika y'Uburundi")]
    #[clap(alias = "République du Burundi")]
    Burundi,
    #[clap(alias = "BE")]
    #[clap(alias = "BE")]
    #[clap(alias = "België")]
    #[clap(alias = "Belgie")]
    #[clap(alias = "Belgien")]
    #[clap(alias = "Belgique")]
    #[clap(alias = "Kingdom of Belgium")]
    #[clap(alias = "Koninkrijk België")]
    #[clap(alias = "Royaume de Belgique")]
    #[clap(alias = "Königreich Belgien")]
    Belgium,
    #[clap(alias = "BJ")]
    #[clap(alias = "BJ")]
    #[clap(alias = "Republic of Benin")]
    #[clap(alias = "République du Bénin")]
    Benin,
    #[clap(alias = "BF")]
    #[clap(alias = "BF")]
    BurkinaFaso,
    #[clap(alias = "BD")]
    #[clap(alias = "BD")]
    #[clap(alias = "People's Republic of Bangladesh")]
    #[clap(alias = "Gônôprôjatôntri Bangladesh")]
    Bangladesh,
    #[clap(alias = "BG")]
    #[clap(alias = "BG")]
    #[clap(alias = "Republic of Bulgaria")]
    #[clap(alias = "Република България")]
    Bulgaria,
    #[clap(alias = "BH")]
    #[clap(alias = "BH")]
    #[clap(alias = "Kingdom of Bahrain")]
    #[clap(alias = "Mamlakat al-Baḥrayn")]
    Bahrain,
    #[clap(alias = "BS")]
    #[clap(alias = "BS")]
    #[clap(alias = "Commonwealth of the Bahamas")]
    Bahamas,
    #[clap(alias = "BA")]
    #[clap(alias = "BA")]
    #[clap(alias = "Bosnia-Herzegovina")]
    #[clap(alias = "Босна и Херцеговина")]
    BosniaAndHerzegovina,
    #[clap(alias = "BL")]
    #[clap(alias = "BL")]
    #[clap(alias = "St. Barthelemy")]
    #[clap(alias = "Collectivity of Saint Barthélemy")]
    #[clap(alias = "Collectivité de Saint-Barthélemy")]
    SaintBarthelemy,
    #[clap(alias = "SH")]
    #[clap(alias = "Saint Helena")]
    #[clap(alias = "St. Helena, Ascension and Tristan da Cunha")]
    SaintHelenaAscensionAndTristanDaCunha,
    #[clap(alias = "BY")]
    #[clap(alias = "BY")]
    #[clap(alias = "Bielaruś")]
    #[clap(alias = "Republic of Belarus")]
    #[clap(alias = "Белоруссия")]
    #[clap(alias = "Республика Белоруссия")]
    Belarus,
    #[clap(alias = "BZ")]
    #[clap(alias = "BZ")]
    Belize,
    #[clap(alias = "BM")]
    #[clap(alias = "BM")]
    #[clap(alias = "The Islands of Bermuda")]
    #[clap(alias = "The Bermudas")]
    #[clap(alias = "Somers Isles")]
    Bermuda,
    #[clap(alias = "BO")]
    #[clap(alias = "BO")]
    #[clap(alias = "Buliwya")]
    #[clap(alias = "Wuliwya")]
    #[clap(alias = "Bolivia, Plurinational State of")]
    #[clap(alias = "Plurinational State of Bolivia")]
    #[clap(alias = "Estado Plurinacional de Bolivia")]
    #[clap(alias = "Buliwya Mamallaqta")]
    #[clap(alias = "Wuliwya Suyu")]
    #[clap(alias = "Tetã Volívia")]
    Bolivia,
    #[clap(alias = "BQ")]
    #[clap(alias = "BES islands")]
    CaribbeanNetherlands,
    #[clap(alias = "BR")]
    #[clap(alias = "BR")]
    #[clap(alias = "Brasil")]
    #[clap(alias = "Federative Republic of Brazil")]
    #[clap(alias = "República Federativa do Brasil")]
    Brazil,
    #[clap(alias = "BB")]
    #[clap(alias = "BB")]
    Barbados,
    #[clap(alias = "BN")]
    #[clap(alias = "BN")]
    #[clap(alias = "Brunei Darussalam")]
    #[clap(alias = "Nation of Brunei")]
    #[clap(alias = "the Abode of Peace")]
    Brunei,
    #[clap(alias = "BT")]
    #[clap(alias = "BT")]
    #[clap(alias = "Kingdom of Bhutan")]
    Bhutan,
    #[clap(alias = "BV")]
    #[clap(alias = "BV")]
    #[clap(alias = "Bouvetøya")]
    #[clap(alias = "Bouvet-øya")]
    BouvetIsland,
    #[clap(alias = "BW")]
    #[clap(alias = "BW")]
    #[clap(alias = "Republic of Botswana")]
    #[clap(alias = "Lefatshe la Botswana")]
    Botswana,
    #[clap(alias = "CF")]
    #[clap(alias = "CF")]
    #[clap(alias = "Central African Republic")]
    #[clap(alias = "République centrafricaine")]
    CentralAfricanRepublic,
    #[clap(alias = "CA")]
    #[clap(alias = "CA")]
    Canada,
    #[clap(alias = "CC")]
    #[clap(alias = "CC")]
    #[clap(alias = "Keeling Islands")]
    #[clap(alias = "Cocos Islands")]
    CocosKeelingIslands,
    #[clap(alias = "CH")]
    #[clap(alias = "CH")]
    #[clap(alias = "Swiss Confederation")]
    #[clap(alias = "Schweiz")]
    #[clap(alias = "Suisse")]
    #[clap(alias = "Svizzera")]
    #[clap(alias = "Svizra")]
    Switzerland,
    #[clap(alias = "CL")]
    #[clap(alias = "CL")]
    #[clap(alias = "Republic of Chile")]
    #[clap(alias = "República de Chile")]
    Chile,
    #[clap(alias = "CN")]
    #[clap(alias = "CN")]
    #[clap(alias = "Zhōngguó")]
    #[clap(alias = "Zhongguo")]
    #[clap(alias = "Zhonghua")]
    #[clap(alias = "People's Republic of China")]
    #[clap(alias = "中华人民共和国")]
    #[clap(alias = "Zhōnghuá Rénmín Gònghéguó")]
    China,
    #[clap(alias = "CI")]
    #[clap(alias = "CI")]
    #[clap(alias = "Côte d'Ivoire")]
    #[clap(alias = "Ivory Coast")]
    #[clap(alias = "Republic of Côte d'Ivoire")]
    #[clap(alias = "République de Côte d'Ivoire")]
    IvoryCoast,
    #[clap(alias = "CM")]
    #[clap(alias = "CM")]
    #[clap(alias = "Republic of Cameroon")]
    #[clap(alias = "République du Cameroun")]
    Cameroon,
    #[clap(alias = "CD")]
    #[clap(alias = "CD")]
    #[clap(alias = "DR Congo")]
    #[clap(alias = "Congo-Kinshasa")]
    #[clap(alias = "Congo, the Democratic Republic of the")]
    #[clap(alias = "DRC")]
    DrCongo,
    #[clap(alias = "CG")]
    #[clap(alias = "CG")]
    #[clap(alias = "Congo")]
    #[clap(alias = "Congo-Brazzaville")]
    RepublicOfTheCongo,
    #[clap(alias = "CK")]
    #[clap(alias = "CK")]
    #[clap(alias = "Kūki 'Āirani")]
    CookIslands,
    #[clap(alias = "CO")]
    #[clap(alias = "CO")]
    #[clap(alias = "Republic of Colombia")]
    #[clap(alias = "República de Colombia")]
    Colombia,
    #[clap(alias = "KM")]
    #[clap(alias = "KM")]
    #[clap(alias = "Union of the Comoros")]
    #[clap(alias = "Union des Comores")]
    #[clap(alias = "Udzima wa Komori")]
    #[clap(alias = "al-Ittiḥād al-Qumurī")]
    Comoros,
    #[clap(alias = "CV")]
    #[clap(alias = "CV")]
    #[clap(alias = "Republic of Cabo Verde")]
    #[clap(alias = "República de Cabo Verde")]
    CapeVerde,
    #[clap(alias = "CR")]
    #[clap(alias = "CR")]
    #[clap(alias = "Republic of Costa Rica")]
    #[clap(alias = "República de Costa Rica")]
    CostaRica,
    #[clap(alias = "CU")]
    #[clap(alias = "CU")]
    #[clap(alias = "Republic of Cuba")]
    #[clap(alias = "República de Cuba")]
    Cuba,
    #[clap(alias = "CW")]
    #[clap(alias = "CW")]
    #[clap(alias = "Curacao")]
    #[clap(alias = "Kòrsou")]
    #[clap(alias = "Country of Curaçao")]
    #[clap(alias = "Land Curaçao")]
    #[clap(alias = "Pais Kòrsou")]
    Curacao,
    #[clap(alias = "CX")]
    #[clap(alias = "CX")]
    #[clap(alias = "Territory of Christmas Island")]
    ChristmasIsland,
    #[clap(alias = "KY")]
    #[clap(alias = "KY")]
    CaymanIslands,
    #[clap(alias = "CY")]
    #[clap(alias = "CY")]
    #[clap(alias = "Kýpros")]
    #[clap(alias = "Kıbrıs")]
    #[clap(alias = "Republic of Cyprus")]
    #[clap(alias = "Κυπριακή Δημοκρατία")]
    #[clap(alias = "Kıbrıs Cumhuriyeti")]
    Cyprus,
    #[clap(alias = "CZ")]
    #[clap(alias = "CZ")]
    #[clap(alias = "Česká republika")]
    #[clap(alias = "Česko")]
    Czechia,
    #[clap(alias = "DE")]
    #[clap(alias = "DE")]
    #[clap(alias = "Federal Republic of Germany")]
    #[clap(alias = "Bundesrepublik Deutschland")]
    Germany,
    #[clap(alias = "DJ")]
    #[clap(alias = "DJ")]
    #[clap(alias = "Jabuuti")]
    #[clap(alias = "Gabuuti")]
    #[clap(alias = "Republic of Djibouti")]
    #[clap(alias = "République de Djibouti")]
    #[clap(alias = "Gabuutih Ummuuno")]
    #[clap(alias = "Jamhuuriyadda Jabuuti")]
    Djibouti,
    #[clap(alias = "DM")]
    #[clap(alias = "DM")]
    #[clap(alias = "Dominique")]
    #[clap(alias = "Wai‘tu kubuli")]
    #[clap(alias = "Commonwealth of Dominica")]
    Dominica,
    #[clap(alias = "DK")]
    #[clap(alias = "DK")]
    #[clap(alias = "Danmark")]
    #[clap(alias = "Kingdom of Denmark")]
    #[clap(alias = "Kongeriget Danmark")]
    Denmark,
    #[clap(alias = "DO")]
    #[clap(alias = "DO")]
    DominicanRepublic,
    #[clap(alias = "DZ")]
    #[clap(alias = "DZ")]
    #[clap(alias = "Dzayer")]
    #[clap(alias = "Algérie")]
    Algeria,
    #[clap(alias = "EC")]
    #[clap(alias = "EC")]
    #[clap(alias = "Republic of Ecuador")]
    #[clap(alias = "República del Ecuador")]
    Ecuador,
    #[clap(alias = "EG")]
    #[clap(alias = "EG")]
    #[clap(alias = "Arab Republic of Egypt")]
    Egypt,
    #[clap(alias = "ER")]
    #[clap(alias = "ER")]
    #[clap(alias = "State of Eritrea")]
    #[clap(alias = "ሃገረ ኤርትራ")]
    #[clap(alias = "Dawlat Iritriyá")]
    #[clap(alias = "ʾErtrā")]
    #[clap(alias = "Iritriyā")]
    Eritrea,
    #[clap(alias = "EH")]
    #[clap(alias = "EH")]
    #[clap(alias = "Taneẓroft Tutrimt")]
    WesternSahara,
    #[clap(alias = "ES")]
    #[clap(alias = "ES")]
    #[clap(alias = "Kingdom of Spain")]
    #[clap(alias = "Reino de España")]
    Spain,
    #[clap(alias = "EE")]
    #[clap(alias = "EE")]
    #[clap(alias = "Eesti")]
    #[clap(alias = "Republic of Estonia")]
    #[clap(alias = "Eesti Vabariik")]
    Estonia,
    #[clap(alias = "ET")]
    #[clap(alias = "ET")]
    #[clap(alias = "ʾĪtyōṗṗyā")]
    #[clap(alias = "Federal Democratic Republic of Ethiopia")]
    #[clap(
        alias = "የኢትዮጵያ ፌዴራላዊ ዲሞክራሲያዊ ሪፐብሊክ"
    )]
    Ethiopia,
    #[clap(alias = "FI")]
    #[clap(alias = "FI")]
    #[clap(alias = "Suomi")]
    #[clap(alias = "Republic of Finland")]
    #[clap(alias = "Suomen tasavalta")]
    #[clap(alias = "Republiken Finland")]
    Finland,
    #[clap(alias = "FJ")]
    #[clap(alias = "FJ")]
    #[clap(alias = "Viti")]
    #[clap(alias = "Republic of Fiji")]
    #[clap(alias = "Matanitu ko Viti")]
    #[clap(alias = "Fijī Gaṇarājya")]
    Fiji,
    #[clap(alias = "FK")]
    #[clap(alias = "FK")]
    #[clap(alias = "Islas Malvinas")]
    #[clap(alias = "Falkland Islands (Malvinas)")]
    FalklandIslands,
    #[clap(alias = "FR")]
    #[clap(alias = "FR")]
    #[clap(alias = "French Republic")]
    #[clap(alias = "République française")]
    France,
    #[clap(alias = "FO")]
    #[clap(alias = "FO")]
    #[clap(alias = "Føroyar")]
    #[clap(alias = "Færøerne")]
    FaroeIslands,
    #[clap(alias = "FM")]
    #[clap(alias = "FM")]
    #[clap(alias = "Federated States of Micronesia")]
    #[clap(alias = "Micronesia, Federated States of")]
    Micronesia,
    #[clap(alias = "GA")]
    #[clap(alias = "GA")]
    #[clap(alias = "Gabonese Republic")]
    #[clap(alias = "République Gabonaise")]
    Gabon,
    #[clap(alias = "GB")]
    #[clap(alias = "GB")]
    #[clap(alias = "UK")]
    #[clap(alias = "Great Britain")]
    UnitedKingdom,
    #[clap(alias = "GE")]
    #[clap(alias = "GE")]
    #[clap(alias = "Sakartvelo")]
    Georgia,
    #[clap(alias = "GG")]
    #[clap(alias = "GG")]
    #[clap(alias = "Bailiwick of Guernsey")]
    #[clap(alias = "Bailliage de Guernesey")]
    Guernsey,
    #[clap(alias = "GH")]
    #[clap(alias = "GH")]
    Ghana,
    #[clap(alias = "GI")]
    #[clap(alias = "GI")]
    Gibraltar,
    #[clap(alias = "GN")]
    #[clap(alias = "GN")]
    #[clap(alias = "Republic of Guinea")]
    #[clap(alias = "République de Guinée")]
    Guinea,
    #[clap(alias = "GP")]
    #[clap(alias = "GP")]
    #[clap(alias = "Gwadloup")]
    Guadeloupe,
    #[clap(alias = "GM")]
    #[clap(alias = "GM")]
    #[clap(alias = "Republic of the Gambia")]
    Gambia,
    #[clap(alias = "GW")]
    #[clap(alias = "GW")]
    #[clap(alias = "Republic of Guinea-Bissau")]
    #[clap(alias = "República da Guiné-Bissau")]
    GuineaBissau,
    #[clap(alias = "GQ")]
    #[clap(alias = "GQ")]
    #[clap(alias = "Republic of Equatorial Guinea")]
    #[clap(alias = "República de Guinea Ecuatorial")]
    #[clap(alias = "République de Guinée équatoriale")]
    #[clap(alias = "República da Guiné Equatorial")]
    EquatorialGuinea,
    #[clap(alias = "GR")]
    #[clap(alias = "GR")]
    #[clap(alias = "Elláda")]
    #[clap(alias = "Hellenic Republic")]
    #[clap(alias = "Ελληνική Δημοκρατία")]
    Greece,
    #[clap(alias = "GD")]
    #[clap(alias = "GD")]
    Grenada,
    #[clap(alias = "GL")]
    #[clap(alias = "GL")]
    #[clap(alias = "Grønland")]
    Greenland,
    #[clap(alias = "GT")]
    #[clap(alias = "GT")]
    Guatemala,
    #[clap(alias = "GF")]
    #[clap(alias = "GF")]
    #[clap(alias = "Guiana")]
    #[clap(alias = "Guyane")]
    FrenchGuiana,
    #[clap(alias = "GU")]
    #[clap(alias = "GU")]
    #[clap(alias = "Guåhån")]
    Guam,
    #[clap(alias = "GY")]
    #[clap(alias = "GY")]
    #[clap(alias = "Co-operative Republic of Guyana")]
    Guyana,
    #[clap(alias = "HK")]
    #[clap(alias = "HK")]
    HongKong,
    #[clap(alias = "HM")]
    #[clap(alias = "HM")]
    #[clap(alias = "Heard Island and McDonald Islands")]
    HeardIslandAndMcDonaldIslands,
    #[clap(alias = "HN")]
    #[clap(alias = "HN")]
    #[clap(alias = "Republic of Honduras")]
    #[clap(alias = "República de Honduras")]
    Honduras,
    #[clap(alias = "HR")]
    #[clap(alias = "HR")]
    #[clap(alias = "Hrvatska")]
    #[clap(alias = "Republic of Croatia")]
    #[clap(alias = "Republika Hrvatska")]
    Croatia,
    #[clap(alias = "HT")]
    #[clap(alias = "HT")]
    #[clap(alias = "Republic of Haiti")]
    #[clap(alias = "République d'Haïti")]
    #[clap(alias = "Repiblik Ayiti")]
    Haiti,
    #[clap(alias = "HU")]
    #[clap(alias = "HU")]
    Hungary,
    #[clap(alias = "ID")]
    #[clap(alias = "ID")]
    #[clap(alias = "Republic of Indonesia")]
    #[clap(alias = "Republik Indonesia")]
    Indonesia,
    #[clap(alias = "IM")]
    #[clap(alias = "IM")]
    #[clap(alias = "Ellan Vannin")]
    #[clap(alias = "Mann")]
    #[clap(alias = "Mannin")]
    IsleOfMan,
    #[clap(alias = "IN")]
    #[clap(alias = "IN")]
    #[clap(alias = "Bhārat")]
    #[clap(alias = "Republic of India")]
    #[clap(alias = "Bharat Ganrajya")]
    #[clap(alias = "இந\u{bcd}திய\u{bbe}")]
    India,
    #[clap(alias = "IO")]
    #[clap(alias = "IO")]
    BritishIndianOceanTerritory,
    #[clap(alias = "IE")]
    #[clap(alias = "IE")]
    #[clap(alias = "Éire")]
    #[clap(alias = "Republic of Ireland")]
    #[clap(alias = "Poblacht na hÉireann")]
    Ireland,
    #[clap(alias = "IR")]
    #[clap(alias = "IR")]
    #[clap(alias = "Islamic Republic of Iran")]
    #[clap(alias = "Iran, Islamic Republic of")]
    #[clap(alias = "Jomhuri-ye Eslāmi-ye Irān")]
    Iran,
    #[clap(alias = "IQ")]
    #[clap(alias = "IQ")]
    #[clap(alias = "Republic of Iraq")]
    #[clap(alias = "Jumhūriyyat al-‘Irāq")]
    Iraq,
    #[clap(alias = "IS")]
    #[clap(alias = "IS")]
    #[clap(alias = "Island")]
    #[clap(alias = "Republic of Iceland")]
    #[clap(alias = "Lýðveldið Ísland")]
    Iceland,
    #[clap(alias = "IL")]
    #[clap(alias = "IL")]
    #[clap(alias = "State of Israel")]
    #[clap(alias = "Medīnat Yisrā'el")]
    Israel,
    #[clap(alias = "IT")]
    #[clap(alias = "IT")]
    #[clap(alias = "Italian Republic")]
    #[clap(alias = "Repubblica italiana")]
    Italy,
    #[clap(alias = "JM")]
    #[clap(alias = "JM")]
    Jamaica,
    #[clap(alias = "JE")]
    #[clap(alias = "JE")]
    #[clap(alias = "Bailiwick of Jersey")]
    #[clap(alias = "Bailliage de Jersey")]
    #[clap(alias = "Bailliage dé Jèrri")]
    Jersey,
    #[clap(alias = "JO")]
    #[clap(alias = "JO")]
    #[clap(alias = "Hashemite Kingdom of Jordan")]
    #[clap(alias = "al-Mamlakah al-Urdunīyah al-Hāshimīyah")]
    Jordan,
    #[clap(alias = "JP")]
    #[clap(alias = "JP")]
    #[clap(alias = "Nippon")]
    #[clap(alias = "Nihon")]
    Japan,
    #[clap(alias = "KZ")]
    #[clap(alias = "KZ")]
    #[clap(alias = "Qazaqstan")]
    #[clap(alias = "Казахстан")]
    #[clap(alias = "Republic of Kazakhstan")]
    #[clap(alias = "Қазақстан Республикасы")]
    #[clap(alias = "Qazaqstan Respublïkası")]
    #[clap(alias = "Республика Казахстан")]
    #[clap(alias = "Respublika Kazakhstan")]
    Kazakhstan,
    #[clap(alias = "KE")]
    #[clap(alias = "KE")]
    #[clap(alias = "Republic of Kenya")]
    #[clap(alias = "Jamhuri ya Kenya")]
    Kenya,
    #[clap(alias = "KG")]
    #[clap(alias = "KG")]
    #[clap(alias = "Киргизия")]
    #[clap(alias = "Kyrgyz Republic")]
    #[clap(alias = "Кыргыз Республикасы")]
    #[clap(alias = "Kyrgyz Respublikasy")]
    Kyrgyzstan,
    #[clap(alias = "KH")]
    #[clap(alias = "KH")]
    #[clap(alias = "Kingdom of Cambodia")]
    Cambodia,
    #[clap(alias = "KI")]
    #[clap(alias = "KI")]
    #[clap(alias = "Republic of Kiribati")]
    #[clap(alias = "Ribaberiki Kiribati")]
    Kiribati,
    #[clap(alias = "KN")]
    #[clap(alias = "KN")]
    #[clap(alias = "Federation of Saint Christopher and Nevis")]
    SaintKittsAndNevis,
    #[clap(alias = "KR")]
    #[clap(alias = "KR")]
    #[clap(alias = "Korea, Republic of")]
    #[clap(alias = "Republic of Korea")]
    #[clap(alias = "남한")]
    #[clap(alias = "남조선")]
    SouthKorea,
    #[clap(alias = "XK")]
    #[clap(alias = "XK")]
    #[clap(alias = "Република Косово")]
    Kosovo,
    #[clap(alias = "KW")]
    #[clap(alias = "KW")]
    #[clap(alias = "State of Kuwait")]
    #[clap(alias = "Dawlat al-Kuwait")]
    Kuwait,
    #[clap(alias = "LA")]
    #[clap(alias = "LA")]
    #[clap(alias = "Lao")]
    #[clap(alias = "Lao People's Democratic Republic")]
    #[clap(alias = "Sathalanalat Paxathipatai Paxaxon Lao")]
    Laos,
    #[clap(alias = "LB")]
    #[clap(alias = "LB")]
    #[clap(alias = "Lebanese Republic")]
    #[clap(alias = "Al-Jumhūrīyah Al-Libnānīyah")]
    Lebanon,
    #[clap(alias = "LR")]
    #[clap(alias = "LR")]
    #[clap(alias = "Republic of Liberia")]
    Liberia,
    #[clap(alias = "LY")]
    #[clap(alias = "LY")]
    #[clap(alias = "State of Libya")]
    #[clap(alias = "Dawlat Libya")]
    Libya,
    #[clap(alias = "LC")]
    #[clap(alias = "LC")]
    SaintLucia,
    #[clap(alias = "LI")]
    #[clap(alias = "LI")]
    #[clap(alias = "Principality of Liechtenstein")]
    #[clap(alias = "Fürstentum Liechtenstein")]
    Liechtenstein,
    #[clap(alias = "LK")]
    #[clap(alias = "LK")]
    #[clap(alias = "ilaṅkai")]
    #[clap(alias = "Democratic Socialist Republic of Sri Lanka")]
    SriLanka,
    #[clap(alias = "LS")]
    #[clap(alias = "LS")]
    #[clap(alias = "Kingdom of Lesotho")]
    #[clap(alias = "Muso oa Lesotho")]
    Lesotho,
    #[clap(alias = "LT")]
    #[clap(alias = "LT")]
    #[clap(alias = "Republic of Lithuania")]
    #[clap(alias = "Lietuvos Respublika")]
    Lithuania,
    #[clap(alias = "LU")]
    #[clap(alias = "LU")]
    #[clap(alias = "Grand Duchy of Luxembourg")]
    #[clap(alias = "Grand-Duché de Luxembourg")]
    #[clap(alias = "Großherzogtum Luxemburg")]
    #[clap(alias = "Groussherzogtum Lëtzebuerg")]
    Luxembourg,
    #[clap(alias = "LV")]
    #[clap(alias = "LV")]
    #[clap(alias = "Republic of Latvia")]
    #[clap(alias = "Latvijas Republika")]
    Latvia,
    #[clap(alias = "MO")]
    #[clap(alias = "MO")]
    #[clap(alias = "澳门")]
    #[clap(alias = "Macao")]
    #[clap(
        alias = "Macao Special Administrative Region of the People's Republic of China"
    )]
    #[clap(alias = "中華人民共和國澳門特別行政區")]
    #[clap(
        alias = "Região Administrativa Especial de Macau da República Popular da China"
    )]
    Macau,
    #[clap(alias = "MF")]
    #[clap(alias = "MF")]
    #[clap(alias = "Collectivity of Saint Martin")]
    #[clap(alias = "Collectivité de Saint-Martin")]
    #[clap(alias = "Saint Martin (French part)")]
    SaintMartin,
    #[clap(alias = "MA")]
    #[clap(alias = "MA")]
    #[clap(alias = "Kingdom of Morocco")]
    #[clap(alias = "Al-Mamlakah al-Maġribiyah")]
    Morocco,
    #[clap(alias = "MC")]
    #[clap(alias = "MC")]
    #[clap(alias = "Principality of Monaco")]
    #[clap(alias = "Principauté de Monaco")]
    Monaco,
    #[clap(alias = "MD")]
    #[clap(alias = "MD")]
    #[clap(alias = "Moldova, Republic of")]
    #[clap(alias = "Republic of Moldova")]
    #[clap(alias = "Republica Moldova")]
    Moldova,
    #[clap(alias = "MG")]
    #[clap(alias = "MG")]
    #[clap(alias = "Republic of Madagascar")]
    #[clap(alias = "Repoblikan'i Madagasikara")]
    #[clap(alias = "République de Madagascar")]
    Madagascar,
    #[clap(alias = "MV")]
    #[clap(alias = "MV")]
    #[clap(alias = "Maldive Islands")]
    #[clap(alias = "Republic of the Maldives")]
    #[clap(alias = "Dhivehi Raajjeyge Jumhooriyya")]
    Maldives,
    #[clap(alias = "MX")]
    #[clap(alias = "MX")]
    #[clap(alias = "Mexicanos")]
    #[clap(alias = "United Mexican States")]
    #[clap(alias = "Estados Unidos Mexicanos")]
    Mexico,
    #[clap(alias = "MH")]
    #[clap(alias = "MH")]
    #[clap(alias = "Republic of the Marshall Islands")]
    #[clap(alias = "Aolepān Aorōkin M\u{327}ajeļ")]
    MarshallIslands,
    #[clap(alias = "MK")]
    #[clap(alias = "MK")]
    #[clap(alias = "The former Yugoslav Republic of Macedonia")]
    #[clap(alias = "Republic of North Macedonia")]
    #[clap(alias = "Macedonia, The Former Yugoslav Republic of")]
    #[clap(alias = "Република Северна Македонија")]
    NorthMacedonia,
    #[clap(alias = "ML")]
    #[clap(alias = "ML")]
    #[clap(alias = "Republic of Mali")]
    #[clap(alias = "République du Mali")]
    Mali,
    #[clap(alias = "MT")]
    #[clap(alias = "MT")]
    #[clap(alias = "Republic of Malta")]
    #[clap(alias = "Repubblika ta' Malta")]
    Malta,
    #[clap(alias = "MM")]
    #[clap(alias = "MM")]
    #[clap(alias = "Burma")]
    #[clap(alias = "Republic of the Union of Myanmar")]
    #[clap(alias = "Pyidaunzu Thanmăda Myăma Nainngandaw")]
    Myanmar,
    #[clap(alias = "ME")]
    #[clap(alias = "ME")]
    #[clap(alias = "Crna Gora")]
    Montenegro,
    #[clap(alias = "MN")]
    #[clap(alias = "MN")]
    Mongolia,
    #[clap(alias = "MP")]
    #[clap(alias = "MP")]
    #[clap(alias = "Commonwealth of the Northern Mariana Islands")]
    #[clap(alias = "Sankattan Siha Na Islas Mariånas")]
    NorthernMarianaIslands,
    #[clap(alias = "MZ")]
    #[clap(alias = "MZ")]
    #[clap(alias = "Republic of Mozambique")]
    #[clap(alias = "República de Moçambique")]
    Mozambique,
    #[clap(alias = "MR")]
    #[clap(alias = "MR")]
    #[clap(alias = "Islamic Republic of Mauritania")]
    #[clap(alias = "al-Jumhūriyyah al-ʾIslāmiyyah al-Mūrītāniyyah")]
    Mauritania,
    #[clap(alias = "MS")]
    #[clap(alias = "MS")]
    Montserrat,
    #[clap(alias = "MQ")]
    #[clap(alias = "MQ")]
    Martinique,
    #[clap(alias = "MU")]
    #[clap(alias = "MU")]
    #[clap(alias = "Republic of Mauritius")]
    #[clap(alias = "République de Maurice")]
    Mauritius,
    #[clap(alias = "MW")]
    #[clap(alias = "MW")]
    #[clap(alias = "Republic of Malawi")]
    Malawi,
    #[clap(alias = "MY")]
    #[clap(alias = "MY")]
    Malaysia,
    #[clap(alias = "YT")]
    #[clap(alias = "YT")]
    #[clap(alias = "Department of Mayotte")]
    #[clap(alias = "Département de Mayotte")]
    Mayotte,
    #[clap(alias = "NA")]
    #[clap(alias = "NA")]
    #[clap(alias = "Namibië")]
    #[clap(alias = "Republic of Namibia")]
    Namibia,
    #[clap(alias = "NC")]
    #[clap(alias = "NC")]
    NewCaledonia,
    #[clap(alias = "NE")]
    #[clap(alias = "NE")]
    #[clap(alias = "Nijar")]
    Niger,
    #[clap(alias = "NF")]
    #[clap(alias = "NF")]
    #[clap(alias = "Territory of Norfolk Island")]
    #[clap(alias = "Teratri of Norf'k Ailen")]
    NorfolkIsland,
    #[clap(alias = "NG")]
    #[clap(alias = "NG")]
    #[clap(alias = "Nijeriya")]
    #[clap(alias = "Naíjíríà")]
    #[clap(alias = "Federal Republic of Nigeria")]
    Nigeria,
    #[clap(alias = "NI")]
    #[clap(alias = "NI")]
    #[clap(alias = "Republic of Nicaragua")]
    #[clap(alias = "República de Nicaragua")]
    Nicaragua,
    #[clap(alias = "NU")]
    #[clap(alias = "NU")]
    Niue,
    #[clap(alias = "NL")]
    #[clap(alias = "NL")]
    #[clap(alias = "Holland")]
    #[clap(alias = "Nederland")]
    #[clap(alias = "The Netherlands")]
    Netherlands,
    #[clap(alias = "NO")]
    #[clap(alias = "NO")]
    #[clap(alias = "Norge")]
    #[clap(alias = "Noreg")]
    #[clap(alias = "Kingdom of Norway")]
    #[clap(alias = "Kongeriket Norge")]
    #[clap(alias = "Kongeriket Noreg")]
    Norway,
    #[clap(alias = "NP")]
    #[clap(alias = "NP")]
    #[clap(alias = "Federal Democratic Republic of Nepal")]
    #[clap(alias = "Loktāntrik Ganatantra Nepāl")]
    Nepal,
    #[clap(alias = "NR")]
    #[clap(alias = "NR")]
    #[clap(alias = "Naoero")]
    #[clap(alias = "Pleasant Island")]
    #[clap(alias = "Republic of Nauru")]
    #[clap(alias = "Ripublik Naoero")]
    Nauru,
    #[clap(alias = "NZ")]
    #[clap(alias = "NZ")]
    #[clap(alias = "Aotearoa")]
    NewZealand,
    #[clap(alias = "OM")]
    #[clap(alias = "OM")]
    #[clap(alias = "Sultanate of Oman")]
    #[clap(alias = "Salṭanat ʻUmān")]
    Oman,
    #[clap(alias = "PK")]
    #[clap(alias = "PK")]
    #[clap(alias = "Pākistān")]
    #[clap(alias = "Islamic Republic of Pakistan")]
    #[clap(alias = "Islāmī Jumhūriya'eh Pākistān")]
    Pakistan,
    #[clap(alias = "PA")]
    #[clap(alias = "PA")]
    #[clap(alias = "Republic of Panama")]
    #[clap(alias = "República de Panamá")]
    Panama,
    #[clap(alias = "PN")]
    #[clap(alias = "PN")]
    #[clap(alias = "Pitcairn")]
    #[clap(alias = "Pitcairn Henderson Ducie and Oeno Islands")]
    PitcairnIslands,
    #[clap(alias = "PE")]
    #[clap(alias = "PE")]
    #[clap(alias = "Republic of Peru")]
    #[clap(alias = "República del Perú")]
    Peru,
    #[clap(alias = "PH")]
    #[clap(alias = "PH")]
    #[clap(alias = "Republic of the Philippines")]
    #[clap(alias = "Repúblika ng Pilipinas")]
    Philippines,
    #[clap(alias = "PW")]
    #[clap(alias = "PW")]
    #[clap(alias = "Republic of Palau")]
    #[clap(alias = "Beluu er a Belau")]
    Palau,
    #[clap(alias = "PG")]
    #[clap(alias = "PG")]
    #[clap(alias = "Independent State of Papua New Guinea")]
    #[clap(alias = "Independen Stet bilong Papua Niugini")]
    PapuaNewGuinea,
    #[clap(alias = "PL")]
    #[clap(alias = "PL")]
    #[clap(alias = "Republic of Poland")]
    #[clap(alias = "Rzeczpospolita Polska")]
    Poland,
    #[clap(alias = "PR")]
    #[clap(alias = "PR")]
    #[clap(alias = "Commonwealth of Puerto Rico")]
    #[clap(alias = "Estado Libre Asociado de Puerto Rico")]
    PuertoRico,
    #[clap(alias = "KP")]
    #[clap(alias = "KP")]
    #[clap(alias = "Democratic People's Republic of Korea")]
    #[clap(alias = "DPRK")]
    #[clap(alias = "조선민주주의인민공화국")]
    #[clap(alias = "Chosŏn Minjujuŭi Inmin Konghwaguk")]
    #[clap(alias = "Korea, Democratic People's Republic of")]
    #[clap(alias = "북한")]
    #[clap(alias = "북조선")]
    NorthKorea,
    #[clap(alias = "PT")]
    #[clap(alias = "PT")]
    #[clap(alias = "Portuguesa")]
    #[clap(alias = "Portuguese Republic")]
    #[clap(alias = "República Portuguesa")]
    Portugal,
    #[clap(alias = "PY")]
    #[clap(alias = "PY")]
    #[clap(alias = "Republic of Paraguay")]
    #[clap(alias = "República del Paraguay")]
    #[clap(alias = "Tetã Paraguái")]
    Paraguay,
    #[clap(alias = "PS")]
    #[clap(alias = "PS")]
    #[clap(alias = "Palestine, State of")]
    #[clap(alias = "State of Palestine")]
    #[clap(alias = "Dawlat Filasṭin")]
    Palestine,
    #[clap(alias = "PF")]
    #[clap(alias = "PF")]
    #[clap(alias = "Polynésie française")]
    #[clap(alias = "French Polynesia")]
    #[clap(alias = "Pōrīnetia Farāni")]
    FrenchPolynesia,
    #[clap(alias = "QA")]
    #[clap(alias = "QA")]
    #[clap(alias = "State of Qatar")]
    #[clap(alias = "Dawlat Qaṭar")]
    Qatar,
    #[clap(alias = "RE")]
    #[clap(alias = "RE")]
    #[clap(alias = "Reunion")]
    Reunion,
    #[clap(alias = "RO")]
    #[clap(alias = "RO")]
    #[clap(alias = "Rumania")]
    #[clap(alias = "Roumania")]
    #[clap(alias = "România")]
    Romania,
    #[clap(alias = "RU")]
    #[clap(alias = "RU")]
    #[clap(alias = "Russian Federation")]
    #[clap(alias = "Российская Федерация")]
    Russia,
    #[clap(alias = "RW")]
    #[clap(alias = "RW")]
    #[clap(alias = "Republic of Rwanda")]
    #[clap(alias = "Repubulika y'u Rwanda")]
    #[clap(alias = "République du Rwanda")]
    Rwanda,
    #[clap(alias = "SA")]
    #[clap(alias = "Saudi")]
    #[clap(alias = "SA")]
    #[clap(alias = "Kingdom of Saudi Arabia")]
    #[clap(alias = "Al-Mamlakah al-‘Arabiyyah as-Su‘ūdiyyah")]
    SaudiArabia,
    #[clap(alias = "SD")]
    #[clap(alias = "SD")]
    #[clap(alias = "Republic of the Sudan")]
    #[clap(alias = "Jumhūrīyat as-Sūdān")]
    Sudan,
    #[clap(alias = "SN")]
    #[clap(alias = "SN")]
    #[clap(alias = "Republic of Senegal")]
    #[clap(alias = "République du Sénégal")]
    Senegal,
    #[clap(alias = "SG")]
    #[clap(alias = "SG")]
    #[clap(alias = "Singapura")]
    #[clap(alias = "Republik Singapura")]
    #[clap(alias = "新加坡共和国")]
    Singapore,
    #[clap(alias = "GS")]
    #[clap(alias = "GS")]
    #[clap(alias = "South Georgia and the South Sandwich Islands")]
    SouthGeorgia,
    #[clap(alias = "SJ")]
    #[clap(alias = "SJ")]
    #[clap(alias = "Svalbard and Jan Mayen Islands")]
    SvalbardAndJanMayen,
    #[clap(alias = "SB")]
    #[clap(alias = "SB")]
    SolomonIslands,
    #[clap(alias = "SL")]
    #[clap(alias = "SL")]
    #[clap(alias = "Republic of Sierra Leone")]
    SierraLeone,
    #[clap(alias = "SV")]
    #[clap(alias = "SV")]
    #[clap(alias = "Republic of El Salvador")]
    #[clap(alias = "República de El Salvador")]
    ElSalvador,
    #[clap(alias = "SM")]
    #[clap(alias = "SM")]
    #[clap(alias = "Republic of San Marino")]
    #[clap(alias = "Repubblica di San Marino")]
    SanMarino,
    #[clap(alias = "SO")]
    #[clap(alias = "SO")]
    #[clap(alias = "aṣ-Ṣūmāl")]
    #[clap(alias = "Federal Republic of Somalia")]
    #[clap(alias = "Jamhuuriyadda Federaalka Soomaaliya")]
    #[clap(alias = "Jumhūriyyat aṣ-Ṣūmāl al-Fiderāliyya")]
    Somalia,
    #[clap(alias = "PM")]
    #[clap(alias = "PM")]
    #[clap(alias = "Collectivité territoriale de Saint-Pierre-et-Miquelon")]
    SaintPierreAndMiquelon,
    #[clap(alias = "RS")]
    #[clap(alias = "RS")]
    #[clap(alias = "Srbija")]
    #[clap(alias = "Republic of Serbia")]
    #[clap(alias = "Република Србија")]
    #[clap(alias = "Republika Srbija")]
    Serbia,
    #[clap(alias = "SS")]
    #[clap(alias = "SS")]
    SouthSudan,
    #[clap(alias = "ST")]
    #[clap(alias = "ST")]
    #[clap(alias = "Democratic Republic of São Tomé and Príncipe")]
    #[clap(alias = "Sao Tome and Principe")]
    #[clap(alias = "República Democrática de São Tomé e Príncipe")]
    SaoTomeAndPrincipe,
    #[clap(alias = "SR")]
    #[clap(alias = "SR")]
    #[clap(alias = "Sarnam")]
    #[clap(alias = "Sranangron")]
    #[clap(alias = "Republic of Suriname")]
    #[clap(alias = "Republiek Suriname")]
    Suriname,
    #[clap(alias = "SK")]
    #[clap(alias = "SK")]
    #[clap(alias = "Slovak Republic")]
    #[clap(alias = "Slovenská republika")]
    Slovakia,
    #[clap(alias = "SI")]
    #[clap(alias = "SI")]
    #[clap(alias = "Republic of Slovenia")]
    #[clap(alias = "Republika Slovenija")]
    Slovenia,
    #[clap(alias = "SE")]
    #[clap(alias = "SE")]
    #[clap(alias = "Kingdom of Sweden")]
    #[clap(alias = "Konungariket Sverige")]
    Sweden,
    #[clap(alias = "SZ")]
    #[clap(alias = "SZ")]
    #[clap(alias = "Swaziland")]
    #[clap(alias = "weSwatini")]
    #[clap(alias = "Swatini")]
    #[clap(alias = "Ngwane")]
    #[clap(alias = "Kingdom of Eswatini")]
    #[clap(alias = "Umbuso weSwatini")]
    Eswatini,
    #[clap(alias = "SX")]
    #[clap(alias = "SX")]
    #[clap(alias = "Sint Maarten (Dutch part)")]
    SintMaarten,
    #[clap(alias = "SC")]
    #[clap(alias = "SC")]
    #[clap(alias = "Republic of Seychelles")]
    #[clap(alias = "Repiblik Sesel")]
    #[clap(alias = "République des Seychelles")]
    Seychelles,
    #[clap(alias = "SY")]
    #[clap(alias = "SY")]
    #[clap(alias = "Syrian Arab Republic")]
    #[clap(alias = "Al-Jumhūrīyah Al-ʻArabīyah As-Sūrīyah")]
    Syria,
    #[clap(alias = "TC")]
    #[clap(alias = "TC")]
    TurksAndCaicosIslands,
    #[clap(alias = "TD")]
    #[clap(alias = "TD")]
    #[clap(alias = "Tchad")]
    #[clap(alias = "Republic of Chad")]
    #[clap(alias = "République du Tchad")]
    Chad,
    #[clap(alias = "TG")]
    #[clap(alias = "TG")]
    #[clap(alias = "Togolese")]
    #[clap(alias = "Togolese Republic")]
    #[clap(alias = "République Togolaise")]
    Togo,
    #[clap(alias = "TH")]
    #[clap(alias = "TH")]
    #[clap(alias = "Prathet")]
    #[clap(alias = "Thai")]
    #[clap(alias = "Kingdom of Thailand")]
    #[clap(alias = "ราชอาณาจ\u{e31}กรไทย")]
    #[clap(alias = "Ratcha Anachak Thai")]
    Thailand,
    #[clap(alias = "TJ")]
    #[clap(alias = "TJ")]
    #[clap(alias = "Toçikiston")]
    #[clap(alias = "Republic of Tajikistan")]
    #[clap(alias = "Ҷумҳурии Тоҷикистон")]
    #[clap(alias = "Çumhuriyi Toçikiston")]
    Tajikistan,
    #[clap(alias = "TK")]
    #[clap(alias = "TK")]
    Tokelau,
    #[clap(alias = "TM")]
    #[clap(alias = "TM")]
    Turkmenistan,
    #[clap(alias = "TL")]
    #[clap(alias = "TL")]
    #[clap(alias = "East Timor")]
    #[clap(alias = "Democratic Republic of Timor-Leste")]
    #[clap(alias = "República Democrática de Timor-Leste")]
    #[clap(alias = "Repúblika Demokrátika Timór-Leste")]
    #[clap(alias = "Timór Lorosa'e")]
    #[clap(alias = "Timor Lorosae")]
    TimorLeste,
    #[clap(alias = "TO")]
    #[clap(alias = "TO")]
    Tonga,
    #[clap(alias = "TT")]
    #[clap(alias = "TT")]
    #[clap(alias = "Republic of Trinidad and Tobago")]
    TrinidadAndTobago,
    #[clap(alias = "TN")]
    #[clap(alias = "TN")]
    #[clap(alias = "Republic of Tunisia")]
    #[clap(alias = "al-Jumhūriyyah at-Tūnisiyyah")]
    Tunisia,
    #[clap(alias = "TR")]
    #[clap(alias = "TR")]
    #[clap(alias = "Turkiye")]
    #[clap(alias = "Republic of Turkey")]
    #[clap(alias = "Türkiye Cumhuriyeti")]
    Turkey,
    #[clap(alias = "TV")]
    #[clap(alias = "TV")]
    Tuvalu,
    #[clap(alias = "TW")]
    #[clap(alias = "TW")]
    #[clap(alias = "Táiwān")]
    #[clap(alias = "Republic of China")]
    #[clap(alias = "中華民國")]
    #[clap(alias = "Zhōnghuá Mínguó")]
    #[clap(alias = "Chinese Taipei")]
    Taiwan,
    #[clap(alias = "TZ")]
    #[clap(alias = "TZ")]
    #[clap(alias = "Tanzania, United Republic of")]
    #[clap(alias = "United Republic of Tanzania")]
    #[clap(alias = "Jamhuri ya Muungano wa Tanzania")]
    Tanzania,
    #[clap(alias = "UG")]
    #[clap(alias = "UG")]
    #[clap(alias = "Republic of Uganda")]
    #[clap(alias = "Jamhuri ya Uganda")]
    Uganda,
    #[clap(alias = "UA")]
    #[clap(alias = "UA")]
    #[clap(alias = "Ukrayina")]
    Ukraine,
    #[clap(alias = "UM")]
    #[clap(alias = "UM")]
    UnitedStatesMinorOutlyingIslands,
    #[clap(alias = "UY")]
    #[clap(alias = "UY")]
    #[clap(alias = "Oriental Republic of Uruguay")]
    #[clap(alias = "República Oriental del Uruguay")]
    Uruguay,
    #[clap(alias = "US")]
    #[clap(alias = "US")]
    #[clap(alias = "USA")]
    #[clap(alias = "United States of America")]
    UnitedStates,
    #[clap(alias = "UZ")]
    #[clap(alias = "UZ")]
    #[clap(alias = "Republic of Uzbekistan")]
    #[clap(alias = "O‘zbekiston Respublikasi")]
    #[clap(alias = "Ўзбекистон Республикаси")]
    Uzbekistan,
    #[clap(alias = "VA")]
    #[clap(alias = "VA")]
    #[clap(alias = "Holy See (Vatican City State)")]
    #[clap(alias = "Vatican City State")]
    #[clap(alias = "Stato della Città del Vaticano")]
    VaticanCity,
    #[clap(alias = "VC")]
    #[clap(alias = "VC")]
    SaintVincentAndTheGrenadines,
    #[clap(alias = "VE")]
    #[clap(alias = "VE")]
    #[clap(alias = "Bolivarian Republic of Venezuela")]
    #[clap(alias = "Venezuela, Bolivarian Republic of")]
    #[clap(alias = "República Bolivariana de Venezuela")]
    Venezuela,
    #[clap(alias = "VG")]
    #[clap(alias = "VG")]
    #[clap(alias = "Virgin Islands, British")]
    BritishVirginIslands,
    #[clap(alias = "VI")]
    #[clap(alias = "VI")]
    #[clap(alias = "Virgin Islands, U.S.")]
    UnitedStatesVirginIslands,
    #[clap(alias = "VN")]
    #[clap(alias = "VN")]
    #[clap(alias = "Socialist Republic of Vietnam")]
    #[clap(alias = "Cộng hòa Xã hội chủ nghĩa Việt Nam")]
    #[clap(alias = "Viet Nam")]
    Vietnam,
    #[clap(alias = "VU")]
    #[clap(alias = "VU")]
    #[clap(alias = "Republic of Vanuatu")]
    #[clap(alias = "Ripablik blong Vanuatu")]
    #[clap(alias = "République de Vanuatu")]
    Vanuatu,
    #[clap(alias = "WF")]
    #[clap(alias = "WF")]
    #[clap(alias = "Territory of the Wallis and Futuna Islands")]
    #[clap(alias = "Territoire des îles Wallis et Futuna")]
    WallisAndFutuna,
    #[clap(alias = "WS")]
    #[clap(alias = "WS")]
    #[clap(alias = "Independent State of Samoa")]
    #[clap(alias = "Malo Saʻoloto Tutoʻatasi o Sāmoa")]
    Samoa,
    #[clap(alias = "YE")]
    #[clap(alias = "YE")]
    #[clap(alias = "Yemeni Republic")]
    #[clap(alias = "al-Jumhūriyyah al-Yamaniyyah")]
    Yemen,
    #[clap(alias = "ZA")]
    #[clap(alias = "ZA")]
    #[clap(alias = "RSA")]
    #[clap(alias = "Suid-Afrika")]
    #[clap(alias = "Republic of South Africa")]
    SouthAfrica,
    #[clap(alias = "ZM")]
    #[clap(alias = "ZM")]
    #[clap(alias = "Republic of Zambia")]
    Zambia,
    #[clap(alias = "ZW")]
    #[clap(alias = "ZW")]
    #[clap(alias = "Republic of Zimbabwe")]
    Zimbabwe,
}
/// Slice containing information about every country
#[rustfmt::skip]
pub fn all_countries() -> [&'static Country; 250usize] {
    [
        &COUNTRIES_DATA.0[0usize],
        &COUNTRIES_DATA.0[1usize],
        &COUNTRIES_DATA.0[2usize],
        &COUNTRIES_DATA.0[3usize],
        &COUNTRIES_DATA.0[4usize],
        &COUNTRIES_DATA.0[5usize],
        &COUNTRIES_DATA.0[6usize],
        &COUNTRIES_DATA.0[7usize],
        &COUNTRIES_DATA.0[8usize],
        &COUNTRIES_DATA.0[9usize],
        &COUNTRIES_DATA.0[10usize],
        &COUNTRIES_DATA.0[11usize],
        &COUNTRIES_DATA.0[12usize],
        &COUNTRIES_DATA.0[13usize],
        &COUNTRIES_DATA.0[14usize],
        &COUNTRIES_DATA.0[15usize],
        &COUNTRIES_DATA.0[16usize],
        &COUNTRIES_DATA.0[17usize],
        &COUNTRIES_DATA.0[18usize],
        &COUNTRIES_DATA.0[19usize],
        &COUNTRIES_DATA.0[20usize],
        &COUNTRIES_DATA.0[21usize],
        &COUNTRIES_DATA.0[22usize],
        &COUNTRIES_DATA.0[23usize],
        &COUNTRIES_DATA.0[24usize],
        &COUNTRIES_DATA.0[25usize],
        &COUNTRIES_DATA.0[26usize],
        &COUNTRIES_DATA.0[27usize],
        &COUNTRIES_DATA.0[28usize],
        &COUNTRIES_DATA.0[29usize],
        &COUNTRIES_DATA.0[30usize],
        &COUNTRIES_DATA.0[31usize],
        &COUNTRIES_DATA.0[32usize],
        &COUNTRIES_DATA.0[33usize],
        &COUNTRIES_DATA.0[34usize],
        &COUNTRIES_DATA.0[35usize],
        &COUNTRIES_DATA.0[36usize],
        &COUNTRIES_DATA.0[37usize],
        &COUNTRIES_DATA.0[38usize],
        &COUNTRIES_DATA.0[39usize],
        &COUNTRIES_DATA.0[40usize],
        &COUNTRIES_DATA.0[41usize],
        &COUNTRIES_DATA.0[42usize],
        &COUNTRIES_DATA.0[43usize],
        &COUNTRIES_DATA.0[44usize],
        &COUNTRIES_DATA.0[45usize],
        &COUNTRIES_DATA.0[46usize],
        &COUNTRIES_DATA.0[47usize],
        &COUNTRIES_DATA.0[48usize],
        &COUNTRIES_DATA.0[49usize],
        &COUNTRIES_DATA.0[50usize],
        &COUNTRIES_DATA.0[51usize],
        &COUNTRIES_DATA.0[52usize],
        &COUNTRIES_DATA.0[53usize],
        &COUNTRIES_DATA.0[54usize],
        &COUNTRIES_DATA.0[55usize],
        &COUNTRIES_DATA.0[56usize],
        &COUNTRIES_DATA.0[57usize],
        &COUNTRIES_DATA.0[58usize],
        &COUNTRIES_DATA.0[59usize],
        &COUNTRIES_DATA.0[60usize],
        &COUNTRIES_DATA.0[61usize],
        &COUNTRIES_DATA.0[62usize],
        &COUNTRIES_DATA.0[63usize],
        &COUNTRIES_DATA.0[64usize],
        &COUNTRIES_DATA.0[65usize],
        &COUNTRIES_DATA.0[66usize],
        &COUNTRIES_DATA.0[67usize],
        &COUNTRIES_DATA.0[68usize],
        &COUNTRIES_DATA.0[69usize],
        &COUNTRIES_DATA.0[70usize],
        &COUNTRIES_DATA.0[71usize],
        &COUNTRIES_DATA.0[72usize],
        &COUNTRIES_DATA.0[73usize],
        &COUNTRIES_DATA.0[74usize],
        &COUNTRIES_DATA.0[75usize],
        &COUNTRIES_DATA.0[76usize],
        &COUNTRIES_DATA.0[77usize],
        &COUNTRIES_DATA.0[78usize],
        &COUNTRIES_DATA.0[79usize],
        &COUNTRIES_DATA.0[80usize],
        &COUNTRIES_DATA.0[81usize],
        &COUNTRIES_DATA.0[82usize],
        &COUNTRIES_DATA.0[83usize],
        &COUNTRIES_DATA.0[84usize],
        &COUNTRIES_DATA.0[85usize],
        &COUNTRIES_DATA.0[86usize],
        &COUNTRIES_DATA.0[87usize],
        &COUNTRIES_DATA.0[88usize],
        &COUNTRIES_DATA.0[89usize],
        &COUNTRIES_DATA.0[90usize],
        &COUNTRIES_DATA.0[91usize],
        &COUNTRIES_DATA.0[92usize],
        &COUNTRIES_DATA.0[93usize],
        &COUNTRIES_DATA.0[94usize],
        &COUNTRIES_DATA.0[95usize],
        &COUNTRIES_DATA.0[96usize],
        &COUNTRIES_DATA.0[97usize],
        &COUNTRIES_DATA.0[98usize],
        &COUNTRIES_DATA.0[99usize],
        &COUNTRIES_DATA.0[100usize],
        &COUNTRIES_DATA.0[101usize],
        &COUNTRIES_DATA.0[102usize],
        &COUNTRIES_DATA.0[103usize],
        &COUNTRIES_DATA.0[104usize],
        &COUNTRIES_DATA.0[105usize],
        &COUNTRIES_DATA.0[106usize],
        &COUNTRIES_DATA.0[107usize],
        &COUNTRIES_DATA.0[108usize],
        &COUNTRIES_DATA.0[109usize],
        &COUNTRIES_DATA.0[110usize],
        &COUNTRIES_DATA.0[111usize],
        &COUNTRIES_DATA.0[112usize],
        &COUNTRIES_DATA.0[113usize],
        &COUNTRIES_DATA.0[114usize],
        &COUNTRIES_DATA.0[115usize],
        &COUNTRIES_DATA.0[116usize],
        &COUNTRIES_DATA.0[117usize],
        &COUNTRIES_DATA.0[118usize],
        &COUNTRIES_DATA.0[119usize],
        &COUNTRIES_DATA.0[120usize],
        &COUNTRIES_DATA.0[121usize],
        &COUNTRIES_DATA.0[122usize],
        &COUNTRIES_DATA.0[123usize],
        &COUNTRIES_DATA.0[124usize],
        &COUNTRIES_DATA.0[125usize],
        &COUNTRIES_DATA.0[126usize],
        &COUNTRIES_DATA.0[127usize],
        &COUNTRIES_DATA.0[128usize],
        &COUNTRIES_DATA.0[129usize],
        &COUNTRIES_DATA.0[130usize],
        &COUNTRIES_DATA.0[131usize],
        &COUNTRIES_DATA.0[132usize],
        &COUNTRIES_DATA.0[133usize],
        &COUNTRIES_DATA.0[134usize],
        &COUNTRIES_DATA.0[135usize],
        &COUNTRIES_DATA.0[136usize],
        &COUNTRIES_DATA.0[137usize],
        &COUNTRIES_DATA.0[138usize],
        &COUNTRIES_DATA.0[139usize],
        &COUNTRIES_DATA.0[140usize],
        &COUNTRIES_DATA.0[141usize],
        &COUNTRIES_DATA.0[142usize],
        &COUNTRIES_DATA.0[143usize],
        &COUNTRIES_DATA.0[144usize],
        &COUNTRIES_DATA.0[145usize],
        &COUNTRIES_DATA.0[146usize],
        &COUNTRIES_DATA.0[147usize],
        &COUNTRIES_DATA.0[148usize],
        &COUNTRIES_DATA.0[149usize],
        &COUNTRIES_DATA.0[150usize],
        &COUNTRIES_DATA.0[151usize],
        &COUNTRIES_DATA.0[152usize],
        &COUNTRIES_DATA.0[153usize],
        &COUNTRIES_DATA.0[154usize],
        &COUNTRIES_DATA.0[155usize],
        &COUNTRIES_DATA.0[156usize],
        &COUNTRIES_DATA.0[157usize],
        &COUNTRIES_DATA.0[158usize],
        &COUNTRIES_DATA.0[159usize],
        &COUNTRIES_DATA.0[160usize],
        &COUNTRIES_DATA.0[161usize],
        &COUNTRIES_DATA.0[162usize],
        &COUNTRIES_DATA.0[163usize],
        &COUNTRIES_DATA.0[164usize],
        &COUNTRIES_DATA.0[165usize],
        &COUNTRIES_DATA.0[166usize],
        &COUNTRIES_DATA.0[167usize],
        &COUNTRIES_DATA.0[168usize],
        &COUNTRIES_DATA.0[169usize],
        &COUNTRIES_DATA.0[170usize],
        &COUNTRIES_DATA.0[171usize],
        &COUNTRIES_DATA.0[172usize],
        &COUNTRIES_DATA.0[173usize],
        &COUNTRIES_DATA.0[174usize],
        &COUNTRIES_DATA.0[175usize],
        &COUNTRIES_DATA.0[176usize],
        &COUNTRIES_DATA.0[177usize],
        &COUNTRIES_DATA.0[178usize],
        &COUNTRIES_DATA.0[179usize],
        &COUNTRIES_DATA.0[180usize],
        &COUNTRIES_DATA.0[181usize],
        &COUNTRIES_DATA.0[182usize],
        &COUNTRIES_DATA.0[183usize],
        &COUNTRIES_DATA.0[184usize],
        &COUNTRIES_DATA.0[185usize],
        &COUNTRIES_DATA.0[186usize],
        &COUNTRIES_DATA.0[187usize],
        &COUNTRIES_DATA.0[188usize],
        &COUNTRIES_DATA.0[189usize],
        &COUNTRIES_DATA.0[190usize],
        &COUNTRIES_DATA.0[191usize],
        &COUNTRIES_DATA.0[192usize],
        &COUNTRIES_DATA.0[193usize],
        &COUNTRIES_DATA.0[194usize],
        &COUNTRIES_DATA.0[195usize],
        &COUNTRIES_DATA.0[196usize],
        &COUNTRIES_DATA.0[197usize],
        &COUNTRIES_DATA.0[198usize],
        &COUNTRIES_DATA.0[199usize],
        &COUNTRIES_DATA.0[200usize],
        &COUNTRIES_DATA.0[201usize],
        &COUNTRIES_DATA.0[202usize],
        &COUNTRIES_DATA.0[203usize],
        &COUNTRIES_DATA.0[204usize],
        &COUNTRIES_DATA.0[205usize],
        &COUNTRIES_DATA.0[206usize],
        &COUNTRIES_DATA.0[207usize],
        &COUNTRIES_DATA.0[208usize],
        &COUNTRIES_DATA.0[209usize],
        &COUNTRIES_DATA.0[210usize],
        &COUNTRIES_DATA.0[211usize],
        &COUNTRIES_DATA.0[212usize],
        &COUNTRIES_DATA.0[213usize],
        &COUNTRIES_DATA.0[214usize],
        &COUNTRIES_DATA.0[215usize],
        &COUNTRIES_DATA.0[216usize],
        &COUNTRIES_DATA.0[217usize],
        &COUNTRIES_DATA.0[218usize],
        &COUNTRIES_DATA.0[219usize],
        &COUNTRIES_DATA.0[220usize],
        &COUNTRIES_DATA.0[221usize],
        &COUNTRIES_DATA.0[222usize],
        &COUNTRIES_DATA.0[223usize],
        &COUNTRIES_DATA.0[224usize],
        &COUNTRIES_DATA.0[225usize],
        &COUNTRIES_DATA.0[226usize],
        &COUNTRIES_DATA.0[227usize],
        &COUNTRIES_DATA.0[228usize],
        &COUNTRIES_DATA.0[229usize],
        &COUNTRIES_DATA.0[230usize],
        &COUNTRIES_DATA.0[231usize],
        &COUNTRIES_DATA.0[232usize],
        &COUNTRIES_DATA.0[233usize],
        &COUNTRIES_DATA.0[234usize],
        &COUNTRIES_DATA.0[235usize],
        &COUNTRIES_DATA.0[236usize],
        &COUNTRIES_DATA.0[237usize],
        &COUNTRIES_DATA.0[238usize],
        &COUNTRIES_DATA.0[239usize],
        &COUNTRIES_DATA.0[240usize],
        &COUNTRIES_DATA.0[241usize],
        &COUNTRIES_DATA.0[242usize],
        &COUNTRIES_DATA.0[243usize],
        &COUNTRIES_DATA.0[244usize],
        &COUNTRIES_DATA.0[245usize],
        &COUNTRIES_DATA.0[246usize],
        &COUNTRIES_DATA.0[247usize],
        &COUNTRIES_DATA.0[248usize],
        &COUNTRIES_DATA.0[249usize],
    ]
}
#[rustfmt::skip]
impl CountryKind {
    /// Data about this specific country
    pub fn data(self) -> &'static Country {
        match self {
            Self::Aruba => &COUNTRIES_DATA.0[0usize],
            Self::Afghanistan => &COUNTRIES_DATA.0[1usize],
            Self::Angola => &COUNTRIES_DATA.0[2usize],
            Self::Anguilla => &COUNTRIES_DATA.0[3usize],
            Self::AlandIslands => &COUNTRIES_DATA.0[4usize],
            Self::Albania => &COUNTRIES_DATA.0[5usize],
            Self::Andorra => &COUNTRIES_DATA.0[6usize],
            Self::UnitedArabEmirates => &COUNTRIES_DATA.0[7usize],
            Self::Argentina => &COUNTRIES_DATA.0[8usize],
            Self::Armenia => &COUNTRIES_DATA.0[9usize],
            Self::AmericanSamoa => &COUNTRIES_DATA.0[10usize],
            Self::Antarctica => &COUNTRIES_DATA.0[11usize],
            Self::FrenchSouthernAndAntarcticLands => &COUNTRIES_DATA.0[12usize],
            Self::AntiguaAndBarbuda => &COUNTRIES_DATA.0[13usize],
            Self::Australia => &COUNTRIES_DATA.0[14usize],
            Self::Austria => &COUNTRIES_DATA.0[15usize],
            Self::Azerbaijan => &COUNTRIES_DATA.0[16usize],
            Self::Burundi => &COUNTRIES_DATA.0[17usize],
            Self::Belgium => &COUNTRIES_DATA.0[18usize],
            Self::Benin => &COUNTRIES_DATA.0[19usize],
            Self::BurkinaFaso => &COUNTRIES_DATA.0[20usize],
            Self::Bangladesh => &COUNTRIES_DATA.0[21usize],
            Self::Bulgaria => &COUNTRIES_DATA.0[22usize],
            Self::Bahrain => &COUNTRIES_DATA.0[23usize],
            Self::Bahamas => &COUNTRIES_DATA.0[24usize],
            Self::BosniaAndHerzegovina => &COUNTRIES_DATA.0[25usize],
            Self::SaintBarthelemy => &COUNTRIES_DATA.0[26usize],
            Self::SaintHelenaAscensionAndTristanDaCunha => &COUNTRIES_DATA.0[27usize],
            Self::Belarus => &COUNTRIES_DATA.0[28usize],
            Self::Belize => &COUNTRIES_DATA.0[29usize],
            Self::Bermuda => &COUNTRIES_DATA.0[30usize],
            Self::Bolivia => &COUNTRIES_DATA.0[31usize],
            Self::CaribbeanNetherlands => &COUNTRIES_DATA.0[32usize],
            Self::Brazil => &COUNTRIES_DATA.0[33usize],
            Self::Barbados => &COUNTRIES_DATA.0[34usize],
            Self::Brunei => &COUNTRIES_DATA.0[35usize],
            Self::Bhutan => &COUNTRIES_DATA.0[36usize],
            Self::BouvetIsland => &COUNTRIES_DATA.0[37usize],
            Self::Botswana => &COUNTRIES_DATA.0[38usize],
            Self::CentralAfricanRepublic => &COUNTRIES_DATA.0[39usize],
            Self::Canada => &COUNTRIES_DATA.0[40usize],
            Self::CocosKeelingIslands => &COUNTRIES_DATA.0[41usize],
            Self::Switzerland => &COUNTRIES_DATA.0[42usize],
            Self::Chile => &COUNTRIES_DATA.0[43usize],
            Self::China => &COUNTRIES_DATA.0[44usize],
            Self::IvoryCoast => &COUNTRIES_DATA.0[45usize],
            Self::Cameroon => &COUNTRIES_DATA.0[46usize],
            Self::DrCongo => &COUNTRIES_DATA.0[47usize],
            Self::RepublicOfTheCongo => &COUNTRIES_DATA.0[48usize],
            Self::CookIslands => &COUNTRIES_DATA.0[49usize],
            Self::Colombia => &COUNTRIES_DATA.0[50usize],
            Self::Comoros => &COUNTRIES_DATA.0[51usize],
            Self::CapeVerde => &COUNTRIES_DATA.0[52usize],
            Self::CostaRica => &COUNTRIES_DATA.0[53usize],
            Self::Cuba => &COUNTRIES_DATA.0[54usize],
            Self::Curacao => &COUNTRIES_DATA.0[55usize],
            Self::ChristmasIsland => &COUNTRIES_DATA.0[56usize],
            Self::CaymanIslands => &COUNTRIES_DATA.0[57usize],
            Self::Cyprus => &COUNTRIES_DATA.0[58usize],
            Self::Czechia => &COUNTRIES_DATA.0[59usize],
            Self::Germany => &COUNTRIES_DATA.0[60usize],
            Self::Djibouti => &COUNTRIES_DATA.0[61usize],
            Self::Dominica => &COUNTRIES_DATA.0[62usize],
            Self::Denmark => &COUNTRIES_DATA.0[63usize],
            Self::DominicanRepublic => &COUNTRIES_DATA.0[64usize],
            Self::Algeria => &COUNTRIES_DATA.0[65usize],
            Self::Ecuador => &COUNTRIES_DATA.0[66usize],
            Self::Egypt => &COUNTRIES_DATA.0[67usize],
            Self::Eritrea => &COUNTRIES_DATA.0[68usize],
            Self::WesternSahara => &COUNTRIES_DATA.0[69usize],
            Self::Spain => &COUNTRIES_DATA.0[70usize],
            Self::Estonia => &COUNTRIES_DATA.0[71usize],
            Self::Ethiopia => &COUNTRIES_DATA.0[72usize],
            Self::Finland => &COUNTRIES_DATA.0[73usize],
            Self::Fiji => &COUNTRIES_DATA.0[74usize],
            Self::FalklandIslands => &COUNTRIES_DATA.0[75usize],
            Self::France => &COUNTRIES_DATA.0[76usize],
            Self::FaroeIslands => &COUNTRIES_DATA.0[77usize],
            Self::Micronesia => &COUNTRIES_DATA.0[78usize],
            Self::Gabon => &COUNTRIES_DATA.0[79usize],
            Self::UnitedKingdom => &COUNTRIES_DATA.0[80usize],
            Self::Georgia => &COUNTRIES_DATA.0[81usize],
            Self::Guernsey => &COUNTRIES_DATA.0[82usize],
            Self::Ghana => &COUNTRIES_DATA.0[83usize],
            Self::Gibraltar => &COUNTRIES_DATA.0[84usize],
            Self::Guinea => &COUNTRIES_DATA.0[85usize],
            Self::Guadeloupe => &COUNTRIES_DATA.0[86usize],
            Self::Gambia => &COUNTRIES_DATA.0[87usize],
            Self::GuineaBissau => &COUNTRIES_DATA.0[88usize],
            Self::EquatorialGuinea => &COUNTRIES_DATA.0[89usize],
            Self::Greece => &COUNTRIES_DATA.0[90usize],
            Self::Grenada => &COUNTRIES_DATA.0[91usize],
            Self::Greenland => &COUNTRIES_DATA.0[92usize],
            Self::Guatemala => &COUNTRIES_DATA.0[93usize],
            Self::FrenchGuiana => &COUNTRIES_DATA.0[94usize],
            Self::Guam => &COUNTRIES_DATA.0[95usize],
            Self::Guyana => &COUNTRIES_DATA.0[96usize],
            Self::HongKong => &COUNTRIES_DATA.0[97usize],
            Self::HeardIslandAndMcDonaldIslands => &COUNTRIES_DATA.0[98usize],
            Self::Honduras => &COUNTRIES_DATA.0[99usize],
            Self::Croatia => &COUNTRIES_DATA.0[100usize],
            Self::Haiti => &COUNTRIES_DATA.0[101usize],
            Self::Hungary => &COUNTRIES_DATA.0[102usize],
            Self::Indonesia => &COUNTRIES_DATA.0[103usize],
            Self::IsleOfMan => &COUNTRIES_DATA.0[104usize],
            Self::India => &COUNTRIES_DATA.0[105usize],
            Self::BritishIndianOceanTerritory => &COUNTRIES_DATA.0[106usize],
            Self::Ireland => &COUNTRIES_DATA.0[107usize],
            Self::Iran => &COUNTRIES_DATA.0[108usize],
            Self::Iraq => &COUNTRIES_DATA.0[109usize],
            Self::Iceland => &COUNTRIES_DATA.0[110usize],
            Self::Israel => &COUNTRIES_DATA.0[111usize],
            Self::Italy => &COUNTRIES_DATA.0[112usize],
            Self::Jamaica => &COUNTRIES_DATA.0[113usize],
            Self::Jersey => &COUNTRIES_DATA.0[114usize],
            Self::Jordan => &COUNTRIES_DATA.0[115usize],
            Self::Japan => &COUNTRIES_DATA.0[116usize],
            Self::Kazakhstan => &COUNTRIES_DATA.0[117usize],
            Self::Kenya => &COUNTRIES_DATA.0[118usize],
            Self::Kyrgyzstan => &COUNTRIES_DATA.0[119usize],
            Self::Cambodia => &COUNTRIES_DATA.0[120usize],
            Self::Kiribati => &COUNTRIES_DATA.0[121usize],
            Self::SaintKittsAndNevis => &COUNTRIES_DATA.0[122usize],
            Self::SouthKorea => &COUNTRIES_DATA.0[123usize],
            Self::Kosovo => &COUNTRIES_DATA.0[124usize],
            Self::Kuwait => &COUNTRIES_DATA.0[125usize],
            Self::Laos => &COUNTRIES_DATA.0[126usize],
            Self::Lebanon => &COUNTRIES_DATA.0[127usize],
            Self::Liberia => &COUNTRIES_DATA.0[128usize],
            Self::Libya => &COUNTRIES_DATA.0[129usize],
            Self::SaintLucia => &COUNTRIES_DATA.0[130usize],
            Self::Liechtenstein => &COUNTRIES_DATA.0[131usize],
            Self::SriLanka => &COUNTRIES_DATA.0[132usize],
            Self::Lesotho => &COUNTRIES_DATA.0[133usize],
            Self::Lithuania => &COUNTRIES_DATA.0[134usize],
            Self::Luxembourg => &COUNTRIES_DATA.0[135usize],
            Self::Latvia => &COUNTRIES_DATA.0[136usize],
            Self::Macau => &COUNTRIES_DATA.0[137usize],
            Self::SaintMartin => &COUNTRIES_DATA.0[138usize],
            Self::Morocco => &COUNTRIES_DATA.0[139usize],
            Self::Monaco => &COUNTRIES_DATA.0[140usize],
            Self::Moldova => &COUNTRIES_DATA.0[141usize],
            Self::Madagascar => &COUNTRIES_DATA.0[142usize],
            Self::Maldives => &COUNTRIES_DATA.0[143usize],
            Self::Mexico => &COUNTRIES_DATA.0[144usize],
            Self::MarshallIslands => &COUNTRIES_DATA.0[145usize],
            Self::NorthMacedonia => &COUNTRIES_DATA.0[146usize],
            Self::Mali => &COUNTRIES_DATA.0[147usize],
            Self::Malta => &COUNTRIES_DATA.0[148usize],
            Self::Myanmar => &COUNTRIES_DATA.0[149usize],
            Self::Montenegro => &COUNTRIES_DATA.0[150usize],
            Self::Mongolia => &COUNTRIES_DATA.0[151usize],
            Self::NorthernMarianaIslands => &COUNTRIES_DATA.0[152usize],
            Self::Mozambique => &COUNTRIES_DATA.0[153usize],
            Self::Mauritania => &COUNTRIES_DATA.0[154usize],
            Self::Montserrat => &COUNTRIES_DATA.0[155usize],
            Self::Martinique => &COUNTRIES_DATA.0[156usize],
            Self::Mauritius => &COUNTRIES_DATA.0[157usize],
            Self::Malawi => &COUNTRIES_DATA.0[158usize],
            Self::Malaysia => &COUNTRIES_DATA.0[159usize],
            Self::Mayotte => &COUNTRIES_DATA.0[160usize],
            Self::Namibia => &COUNTRIES_DATA.0[161usize],
            Self::NewCaledonia => &COUNTRIES_DATA.0[162usize],
            Self::Niger => &COUNTRIES_DATA.0[163usize],
            Self::NorfolkIsland => &COUNTRIES_DATA.0[164usize],
            Self::Nigeria => &COUNTRIES_DATA.0[165usize],
            Self::Nicaragua => &COUNTRIES_DATA.0[166usize],
            Self::Niue => &COUNTRIES_DATA.0[167usize],
            Self::Netherlands => &COUNTRIES_DATA.0[168usize],
            Self::Norway => &COUNTRIES_DATA.0[169usize],
            Self::Nepal => &COUNTRIES_DATA.0[170usize],
            Self::Nauru => &COUNTRIES_DATA.0[171usize],
            Self::NewZealand => &COUNTRIES_DATA.0[172usize],
            Self::Oman => &COUNTRIES_DATA.0[173usize],
            Self::Pakistan => &COUNTRIES_DATA.0[174usize],
            Self::Panama => &COUNTRIES_DATA.0[175usize],
            Self::PitcairnIslands => &COUNTRIES_DATA.0[176usize],
            Self::Peru => &COUNTRIES_DATA.0[177usize],
            Self::Philippines => &COUNTRIES_DATA.0[178usize],
            Self::Palau => &COUNTRIES_DATA.0[179usize],
            Self::PapuaNewGuinea => &COUNTRIES_DATA.0[180usize],
            Self::Poland => &COUNTRIES_DATA.0[181usize],
            Self::PuertoRico => &COUNTRIES_DATA.0[182usize],
            Self::NorthKorea => &COUNTRIES_DATA.0[183usize],
            Self::Portugal => &COUNTRIES_DATA.0[184usize],
            Self::Paraguay => &COUNTRIES_DATA.0[185usize],
            Self::Palestine => &COUNTRIES_DATA.0[186usize],
            Self::FrenchPolynesia => &COUNTRIES_DATA.0[187usize],
            Self::Qatar => &COUNTRIES_DATA.0[188usize],
            Self::Reunion => &COUNTRIES_DATA.0[189usize],
            Self::Romania => &COUNTRIES_DATA.0[190usize],
            Self::Russia => &COUNTRIES_DATA.0[191usize],
            Self::Rwanda => &COUNTRIES_DATA.0[192usize],
            Self::SaudiArabia => &COUNTRIES_DATA.0[193usize],
            Self::Sudan => &COUNTRIES_DATA.0[194usize],
            Self::Senegal => &COUNTRIES_DATA.0[195usize],
            Self::Singapore => &COUNTRIES_DATA.0[196usize],
            Self::SouthGeorgia => &COUNTRIES_DATA.0[197usize],
            Self::SvalbardAndJanMayen => &COUNTRIES_DATA.0[198usize],
            Self::SolomonIslands => &COUNTRIES_DATA.0[199usize],
            Self::SierraLeone => &COUNTRIES_DATA.0[200usize],
            Self::ElSalvador => &COUNTRIES_DATA.0[201usize],
            Self::SanMarino => &COUNTRIES_DATA.0[202usize],
            Self::Somalia => &COUNTRIES_DATA.0[203usize],
            Self::SaintPierreAndMiquelon => &COUNTRIES_DATA.0[204usize],
            Self::Serbia => &COUNTRIES_DATA.0[205usize],
            Self::SouthSudan => &COUNTRIES_DATA.0[206usize],
            Self::SaoTomeAndPrincipe => &COUNTRIES_DATA.0[207usize],
            Self::Suriname => &COUNTRIES_DATA.0[208usize],
            Self::Slovakia => &COUNTRIES_DATA.0[209usize],
            Self::Slovenia => &COUNTRIES_DATA.0[210usize],
            Self::Sweden => &COUNTRIES_DATA.0[211usize],
            Self::Eswatini => &COUNTRIES_DATA.0[212usize],
            Self::SintMaarten => &COUNTRIES_DATA.0[213usize],
            Self::Seychelles => &COUNTRIES_DATA.0[214usize],
            Self::Syria => &COUNTRIES_DATA.0[215usize],
            Self::TurksAndCaicosIslands => &COUNTRIES_DATA.0[216usize],
            Self::Chad => &COUNTRIES_DATA.0[217usize],
            Self::Togo => &COUNTRIES_DATA.0[218usize],
            Self::Thailand => &COUNTRIES_DATA.0[219usize],
            Self::Tajikistan => &COUNTRIES_DATA.0[220usize],
            Self::Tokelau => &COUNTRIES_DATA.0[221usize],
            Self::Turkmenistan => &COUNTRIES_DATA.0[222usize],
            Self::TimorLeste => &COUNTRIES_DATA.0[223usize],
            Self::Tonga => &COUNTRIES_DATA.0[224usize],
            Self::TrinidadAndTobago => &COUNTRIES_DATA.0[225usize],
            Self::Tunisia => &COUNTRIES_DATA.0[226usize],
            Self::Turkey => &COUNTRIES_DATA.0[227usize],
            Self::Tuvalu => &COUNTRIES_DATA.0[228usize],
            Self::Taiwan => &COUNTRIES_DATA.0[229usize],
            Self::Tanzania => &COUNTRIES_DATA.0[230usize],
            Self::Uganda => &COUNTRIES_DATA.0[231usize],
            Self::Ukraine => &COUNTRIES_DATA.0[232usize],
            Self::UnitedStatesMinorOutlyingIslands => &COUNTRIES_DATA.0[233usize],
            Self::Uruguay => &COUNTRIES_DATA.0[234usize],
            Self::UnitedStates => &COUNTRIES_DATA.0[235usize],
            Self::Uzbekistan => &COUNTRIES_DATA.0[236usize],
            Self::VaticanCity => &COUNTRIES_DATA.0[237usize],
            Self::SaintVincentAndTheGrenadines => &COUNTRIES_DATA.0[238usize],
            Self::Venezuela => &COUNTRIES_DATA.0[239usize],
            Self::BritishVirginIslands => &COUNTRIES_DATA.0[240usize],
            Self::UnitedStatesVirginIslands => &COUNTRIES_DATA.0[241usize],
            Self::Vietnam => &COUNTRIES_DATA.0[242usize],
            Self::Vanuatu => &COUNTRIES_DATA.0[243usize],
            Self::WallisAndFutuna => &COUNTRIES_DATA.0[244usize],
            Self::Samoa => &COUNTRIES_DATA.0[245usize],
            Self::Yemen => &COUNTRIES_DATA.0[246usize],
            Self::SouthAfrica => &COUNTRIES_DATA.0[247usize],
            Self::Zambia => &COUNTRIES_DATA.0[248usize],
            Self::Zimbabwe => &COUNTRIES_DATA.0[249usize],
        }
    }
}
#[rustfmt::skip]
impl Country {
    pub fn kind(&self) -> CountryKind {
        match self.country_id {
            0usize => CountryKind::Aruba,
            1usize => CountryKind::Afghanistan,
            2usize => CountryKind::Angola,
            3usize => CountryKind::Anguilla,
            4usize => CountryKind::AlandIslands,
            5usize => CountryKind::Albania,
            6usize => CountryKind::Andorra,
            7usize => CountryKind::UnitedArabEmirates,
            8usize => CountryKind::Argentina,
            9usize => CountryKind::Armenia,
            10usize => CountryKind::AmericanSamoa,
            11usize => CountryKind::Antarctica,
            12usize => CountryKind::FrenchSouthernAndAntarcticLands,
            13usize => CountryKind::AntiguaAndBarbuda,
            14usize => CountryKind::Australia,
            15usize => CountryKind::Austria,
            16usize => CountryKind::Azerbaijan,
            17usize => CountryKind::Burundi,
            18usize => CountryKind::Belgium,
            19usize => CountryKind::Benin,
            20usize => CountryKind::BurkinaFaso,
            21usize => CountryKind::Bangladesh,
            22usize => CountryKind::Bulgaria,
            23usize => CountryKind::Bahrain,
            24usize => CountryKind::Bahamas,
            25usize => CountryKind::BosniaAndHerzegovina,
            26usize => CountryKind::SaintBarthelemy,
            27usize => CountryKind::SaintHelenaAscensionAndTristanDaCunha,
            28usize => CountryKind::Belarus,
            29usize => CountryKind::Belize,
            30usize => CountryKind::Bermuda,
            31usize => CountryKind::Bolivia,
            32usize => CountryKind::CaribbeanNetherlands,
            33usize => CountryKind::Brazil,
            34usize => CountryKind::Barbados,
            35usize => CountryKind::Brunei,
            36usize => CountryKind::Bhutan,
            37usize => CountryKind::BouvetIsland,
            38usize => CountryKind::Botswana,
            39usize => CountryKind::CentralAfricanRepublic,
            40usize => CountryKind::Canada,
            41usize => CountryKind::CocosKeelingIslands,
            42usize => CountryKind::Switzerland,
            43usize => CountryKind::Chile,
            44usize => CountryKind::China,
            45usize => CountryKind::IvoryCoast,
            46usize => CountryKind::Cameroon,
            47usize => CountryKind::DrCongo,
            48usize => CountryKind::RepublicOfTheCongo,
            49usize => CountryKind::CookIslands,
            50usize => CountryKind::Colombia,
            51usize => CountryKind::Comoros,
            52usize => CountryKind::CapeVerde,
            53usize => CountryKind::CostaRica,
            54usize => CountryKind::Cuba,
            55usize => CountryKind::Curacao,
            56usize => CountryKind::ChristmasIsland,
            57usize => CountryKind::CaymanIslands,
            58usize => CountryKind::Cyprus,
            59usize => CountryKind::Czechia,
            60usize => CountryKind::Germany,
            61usize => CountryKind::Djibouti,
            62usize => CountryKind::Dominica,
            63usize => CountryKind::Denmark,
            64usize => CountryKind::DominicanRepublic,
            65usize => CountryKind::Algeria,
            66usize => CountryKind::Ecuador,
            67usize => CountryKind::Egypt,
            68usize => CountryKind::Eritrea,
            69usize => CountryKind::WesternSahara,
            70usize => CountryKind::Spain,
            71usize => CountryKind::Estonia,
            72usize => CountryKind::Ethiopia,
            73usize => CountryKind::Finland,
            74usize => CountryKind::Fiji,
            75usize => CountryKind::FalklandIslands,
            76usize => CountryKind::France,
            77usize => CountryKind::FaroeIslands,
            78usize => CountryKind::Micronesia,
            79usize => CountryKind::Gabon,
            80usize => CountryKind::UnitedKingdom,
            81usize => CountryKind::Georgia,
            82usize => CountryKind::Guernsey,
            83usize => CountryKind::Ghana,
            84usize => CountryKind::Gibraltar,
            85usize => CountryKind::Guinea,
            86usize => CountryKind::Guadeloupe,
            87usize => CountryKind::Gambia,
            88usize => CountryKind::GuineaBissau,
            89usize => CountryKind::EquatorialGuinea,
            90usize => CountryKind::Greece,
            91usize => CountryKind::Grenada,
            92usize => CountryKind::Greenland,
            93usize => CountryKind::Guatemala,
            94usize => CountryKind::FrenchGuiana,
            95usize => CountryKind::Guam,
            96usize => CountryKind::Guyana,
            97usize => CountryKind::HongKong,
            98usize => CountryKind::HeardIslandAndMcDonaldIslands,
            99usize => CountryKind::Honduras,
            100usize => CountryKind::Croatia,
            101usize => CountryKind::Haiti,
            102usize => CountryKind::Hungary,
            103usize => CountryKind::Indonesia,
            104usize => CountryKind::IsleOfMan,
            105usize => CountryKind::India,
            106usize => CountryKind::BritishIndianOceanTerritory,
            107usize => CountryKind::Ireland,
            108usize => CountryKind::Iran,
            109usize => CountryKind::Iraq,
            110usize => CountryKind::Iceland,
            111usize => CountryKind::Israel,
            112usize => CountryKind::Italy,
            113usize => CountryKind::Jamaica,
            114usize => CountryKind::Jersey,
            115usize => CountryKind::Jordan,
            116usize => CountryKind::Japan,
            117usize => CountryKind::Kazakhstan,
            118usize => CountryKind::Kenya,
            119usize => CountryKind::Kyrgyzstan,
            120usize => CountryKind::Cambodia,
            121usize => CountryKind::Kiribati,
            122usize => CountryKind::SaintKittsAndNevis,
            123usize => CountryKind::SouthKorea,
            124usize => CountryKind::Kosovo,
            125usize => CountryKind::Kuwait,
            126usize => CountryKind::Laos,
            127usize => CountryKind::Lebanon,
            128usize => CountryKind::Liberia,
            129usize => CountryKind::Libya,
            130usize => CountryKind::SaintLucia,
            131usize => CountryKind::Liechtenstein,
            132usize => CountryKind::SriLanka,
            133usize => CountryKind::Lesotho,
            134usize => CountryKind::Lithuania,
            135usize => CountryKind::Luxembourg,
            136usize => CountryKind::Latvia,
            137usize => CountryKind::Macau,
            138usize => CountryKind::SaintMartin,
            139usize => CountryKind::Morocco,
            140usize => CountryKind::Monaco,
            141usize => CountryKind::Moldova,
            142usize => CountryKind::Madagascar,
            143usize => CountryKind::Maldives,
            144usize => CountryKind::Mexico,
            145usize => CountryKind::MarshallIslands,
            146usize => CountryKind::NorthMacedonia,
            147usize => CountryKind::Mali,
            148usize => CountryKind::Malta,
            149usize => CountryKind::Myanmar,
            150usize => CountryKind::Montenegro,
            151usize => CountryKind::Mongolia,
            152usize => CountryKind::NorthernMarianaIslands,
            153usize => CountryKind::Mozambique,
            154usize => CountryKind::Mauritania,
            155usize => CountryKind::Montserrat,
            156usize => CountryKind::Martinique,
            157usize => CountryKind::Mauritius,
            158usize => CountryKind::Malawi,
            159usize => CountryKind::Malaysia,
            160usize => CountryKind::Mayotte,
            161usize => CountryKind::Namibia,
            162usize => CountryKind::NewCaledonia,
            163usize => CountryKind::Niger,
            164usize => CountryKind::NorfolkIsland,
            165usize => CountryKind::Nigeria,
            166usize => CountryKind::Nicaragua,
            167usize => CountryKind::Niue,
            168usize => CountryKind::Netherlands,
            169usize => CountryKind::Norway,
            170usize => CountryKind::Nepal,
            171usize => CountryKind::Nauru,
            172usize => CountryKind::NewZealand,
            173usize => CountryKind::Oman,
            174usize => CountryKind::Pakistan,
            175usize => CountryKind::Panama,
            176usize => CountryKind::PitcairnIslands,
            177usize => CountryKind::Peru,
            178usize => CountryKind::Philippines,
            179usize => CountryKind::Palau,
            180usize => CountryKind::PapuaNewGuinea,
            181usize => CountryKind::Poland,
            182usize => CountryKind::PuertoRico,
            183usize => CountryKind::NorthKorea,
            184usize => CountryKind::Portugal,
            185usize => CountryKind::Paraguay,
            186usize => CountryKind::Palestine,
            187usize => CountryKind::FrenchPolynesia,
            188usize => CountryKind::Qatar,
            189usize => CountryKind::Reunion,
            190usize => CountryKind::Romania,
            191usize => CountryKind::Russia,
            192usize => CountryKind::Rwanda,
            193usize => CountryKind::SaudiArabia,
            194usize => CountryKind::Sudan,
            195usize => CountryKind::Senegal,
            196usize => CountryKind::Singapore,
            197usize => CountryKind::SouthGeorgia,
            198usize => CountryKind::SvalbardAndJanMayen,
            199usize => CountryKind::SolomonIslands,
            200usize => CountryKind::SierraLeone,
            201usize => CountryKind::ElSalvador,
            202usize => CountryKind::SanMarino,
            203usize => CountryKind::Somalia,
            204usize => CountryKind::SaintPierreAndMiquelon,
            205usize => CountryKind::Serbia,
            206usize => CountryKind::SouthSudan,
            207usize => CountryKind::SaoTomeAndPrincipe,
            208usize => CountryKind::Suriname,
            209usize => CountryKind::Slovakia,
            210usize => CountryKind::Slovenia,
            211usize => CountryKind::Sweden,
            212usize => CountryKind::Eswatini,
            213usize => CountryKind::SintMaarten,
            214usize => CountryKind::Seychelles,
            215usize => CountryKind::Syria,
            216usize => CountryKind::TurksAndCaicosIslands,
            217usize => CountryKind::Chad,
            218usize => CountryKind::Togo,
            219usize => CountryKind::Thailand,
            220usize => CountryKind::Tajikistan,
            221usize => CountryKind::Tokelau,
            222usize => CountryKind::Turkmenistan,
            223usize => CountryKind::TimorLeste,
            224usize => CountryKind::Tonga,
            225usize => CountryKind::TrinidadAndTobago,
            226usize => CountryKind::Tunisia,
            227usize => CountryKind::Turkey,
            228usize => CountryKind::Tuvalu,
            229usize => CountryKind::Taiwan,
            230usize => CountryKind::Tanzania,
            231usize => CountryKind::Uganda,
            232usize => CountryKind::Ukraine,
            233usize => CountryKind::UnitedStatesMinorOutlyingIslands,
            234usize => CountryKind::Uruguay,
            235usize => CountryKind::UnitedStates,
            236usize => CountryKind::Uzbekistan,
            237usize => CountryKind::VaticanCity,
            238usize => CountryKind::SaintVincentAndTheGrenadines,
            239usize => CountryKind::Venezuela,
            240usize => CountryKind::BritishVirginIslands,
            241usize => CountryKind::UnitedStatesVirginIslands,
            242usize => CountryKind::Vietnam,
            243usize => CountryKind::Vanuatu,
            244usize => CountryKind::WallisAndFutuna,
            245usize => CountryKind::Samoa,
            246usize => CountryKind::Yemen,
            247usize => CountryKind::SouthAfrica,
            248usize => CountryKind::Zambia,
            249usize => CountryKind::Zimbabwe,
            _ => panic!("unknown `country_id`"),
        }
    }
}
